
var onset_trial_stimuli = [
  {
    "index": "1",
    "set": "BAA_PAA_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_5_23.mp3"
  },
  {
    "index": "2",
    "set": "BAH_PAH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAH_PAH_3_20.mp3"
  },
  {
    "index": "3",
    "set": "BIH_PIH_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BIH_PIH_1_21.mp3"
  },
  {
    "index": "4",
    "set": "BUH_PUH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BUH_PUH_3_17.mp3"
  },
  {
    "index": "5",
    "set": "DAA_TAA_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAA_TAA_3_21.mp3"
  },
  {
    "index": "6",
    "set": "DAH_TAH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAH_TAH_3_24.mp3"
  },
  {
    "index": "7",
    "set": "DIH_TIH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DIH_TIH_3_20.mp3"
  },
  {
    "index": "8",
    "set": "DUH_TUH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DUH_TUH_3_23.mp3"
  },
  {
    "index": "9",
    "set": "GAA_KAA_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAA_KAA_5_24.mp3"
  },
  {
    "index": "10",
    "set": "GAH_KAH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAH_KAH_3_18.mp3"
  },
  {
    "index": "11",
    "set": "GIH_KIH_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GIH_KIH_5_22.mp3"
  },
  {
    "index": "12",
    "set": "GUH_KUH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GUH_KUH_3_18.mp3"
  },
  {
    "index": "13",
    "set": "BAA_PAA_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_5_17.mp3"
  },
  {
    "index": "14",
    "set": "BAH_PAH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAH_PAH_3_14.mp3"
  },
  {
    "index": "15",
    "set": "BIH_PIH_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BIH_PIH_1_15.mp3"
  },
  {
    "index": "16",
    "set": "BUH_PUH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BUH_PUH_3_11.mp3"
  },
  {
    "index": "17",
    "set": "DAA_TAA_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAA_TAA_3_15.mp3"
  },
  {
    "index": "18",
    "set": "DAH_TAH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAH_TAH_3_18.mp3"
  },
  {
    "index": "19",
    "set": "DIH_TIH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DIH_TIH_3_14.mp3"
  },
  {
    "index": "20",
    "set": "DUH_TUH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DUH_TUH_3_17.mp3"
  },
  {
    "index": "21",
    "set": "GAA_KAA_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAA_KAA_5_18.mp3"
  },
  {
    "index": "22",
    "set": "GAH_KAH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAH_KAH_3_12.mp3"
  },
  {
    "index": "23",
    "set": "GIH_KIH_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GIH_KIH_5_16.mp3"
  },
  {
    "index": "24",
    "set": "GUH_KUH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GUH_KUH_3_12.mp3"
  },
  {
    "index": "25",
    "set": "BAA_PAA_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_5_19.mp3"
  },
  {
    "index": "26",
    "set": "BAH_PAH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAH_PAH_3_16.mp3"
  },
  {
    "index": "27",
    "set": "BIH_PIH_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BIH_PIH_1_17.mp3"
  },
  {
    "index": "28",
    "set": "BUH_PUH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BUH_PUH_3_13.mp3"
  },
  {
    "index": "29",
    "set": "DAA_TAA_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAA_TAA_3_17.mp3"
  },
  {
    "index": "30",
    "set": "DAH_TAH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAH_TAH_3_20.mp3"
  },
  {
    "index": "31",
    "set": "DIH_TIH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DIH_TIH_3_16.mp3"
  },
  {
    "index": "32",
    "set": "DUH_TUH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DUH_TUH_3_19.mp3"
  },
  {
    "index": "33",
    "set": "GAA_KAA_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAA_KAA_5_20.mp3"
  },
  {
    "index": "34",
    "set": "GAH_KAH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAH_KAH_3_14.mp3"
  },
  {
    "index": "35",
    "set": "GIH_KIH_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GIH_KIH_5_18.mp3"
  },
  {
    "index": "36",
    "set": "GUH_KUH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GUH_KUH_3_14.mp3"
  },
  {
    "index": "37",
    "set": "BAA_PAA_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_5_21.mp3"
  },
  {
    "index": "38",
    "set": "BAH_PAH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAH_PAH_3_18.mp3"
  },
  {
    "index": "39",
    "set": "BIH_PIH_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BIH_PIH_1_19.mp3"
  },
  {
    "index": "40",
    "set": "BUH_PUH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BUH_PUH_3_15.mp3"
  },
  {
    "index": "41",
    "set": "DAA_TAA_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAA_TAA_3_19.mp3"
  },
  {
    "index": "42",
    "set": "DAH_TAH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAH_TAH_3_22.mp3"
  },
  {
    "index": "43",
    "set": "DIH_TIH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DIH_TIH_3_18.mp3"
  },
  {
    "index": "44",
    "set": "DUH_TUH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DUH_TUH_3_21.mp3"
  },
  {
    "index": "45",
    "set": "GAA_KAA_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAA_KAA_5_22.mp3"
  },
  {
    "index": "46",
    "set": "GAH_KAH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAH_KAH_3_16.mp3"
  },
  {
    "index": "47",
    "set": "GIH_KIH_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GIH_KIH_5_20.mp3"
  },
  {
    "index": "48",
    "set": "GUH_KUH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GUH_KUH_3_16.mp3"
  },
  {
    "index": "49",
    "set": "BAA_PAA_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_5_25.mp3"
  },
  {
    "index": "50",
    "set": "BAH_PAH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAH_PAH_3_22.mp3"
  },
  {
    "index": "51",
    "set": "BIH_PIH_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BIH_PIH_1_23.mp3"
  },
  {
    "index": "52",
    "set": "BUH_PUH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BUH_PUH_3_19.mp3"
  },
  {
    "index": "53",
    "set": "DAA_TAA_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAA_TAA_3_23.mp3"
  },
  {
    "index": "54",
    "set": "DAH_TAH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAH_TAH_3_26.mp3"
  },
  {
    "index": "55",
    "set": "DIH_TIH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DIH_TIH_3_22.mp3"
  },
  {
    "index": "56",
    "set": "DUH_TUH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DUH_TUH_3_25.mp3"
  },
  {
    "index": "57",
    "set": "GAA_KAA_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAA_KAA_5_26.mp3"
  },
  {
    "index": "58",
    "set": "GAH_KAH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAH_KAH_3_20.mp3"
  },
  {
    "index": "59",
    "set": "GIH_KIH_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GIH_KIH_5_24.mp3"
  },
  {
    "index": "60",
    "set": "GUH_KUH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GUH_KUH_3_20.mp3"
  },
  {
    "index": "61",
    "set": "BAA_PAA_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_5_27.mp3"
  },
  {
    "index": "62",
    "set": "BAH_PAH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAH_PAH_3_24.mp3"
  },
  {
    "index": "63",
    "set": "BIH_PIH_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BIH_PIH_1_25.mp3"
  },
  {
    "index": "64",
    "set": "BUH_PUH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BUH_PUH_3_21.mp3"
  },
  {
    "index": "65",
    "set": "DAA_TAA_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAA_TAA_3_25.mp3"
  },
  {
    "index": "66",
    "set": "DAH_TAH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAH_TAH_3_28.mp3"
  },
  {
    "index": "67",
    "set": "DIH_TIH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DIH_TIH_3_24.mp3"
  },
  {
    "index": "68",
    "set": "DUH_TUH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DUH_TUH_3_27.mp3"
  },
  {
    "index": "69",
    "set": "GAA_KAA_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAA_KAA_5_28.mp3"
  },
  {
    "index": "70",
    "set": "GAH_KAH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAH_KAH_3_22.mp3"
  },
  {
    "index": "71",
    "set": "GIH_KIH_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GIH_KIH_5_26.mp3"
  },
  {
    "index": "72",
    "set": "GUH_KUH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GUH_KUH_3_22.mp3"
  },
  {
    "index": "73",
    "set": "BAA_PAA_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "29",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_5_29.mp3"
  },
  {
    "index": "74",
    "set": "BAH_PAH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAH_PAH_3_26.mp3"
  },
  {
    "index": "75",
    "set": "BIH_PIH_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BIH_PIH_1_27.mp3"
  },
  {
    "index": "76",
    "set": "BUH_PUH_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BUH_PUH_3_23.mp3"
  },
  {
    "index": "77",
    "set": "DAA_TAA_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAA_TAA_3_27.mp3"
  },
  {
    "index": "78",
    "set": "DAH_TAH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "30",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DAH_TAH_3_30.mp3"
  },
  {
    "index": "79",
    "set": "DIH_TIH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DIH_TIH_3_26.mp3"
  },
  {
    "index": "80",
    "set": "DUH_TUH_3",
    "voiced": "D",
    "voiceless": "T",
    "step": "29",
    "underscore": "_",
    "extension": ".mp3",
    "path": "DUH_TUH_3_29.mp3"
  },
  {
    "index": "81",
    "set": "GAA_KAA_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "30",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAA_KAA_5_30.mp3"
  },
  {
    "index": "82",
    "set": "GAH_KAH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GAH_KAH_3_24.mp3"
  },
  {
    "index": "83",
    "set": "GIH_KIH_5",
    "voiced": "G",
    "voiceless": "K",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GIH_KIH_5_28.mp3"
  },
  {
    "index": "84",
    "set": "GUH_KUH_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "GUH_KUH_3_24.mp3"
  }
]

var coda_trial_stimuli = [
  {
    "index": "1",
    "set": "AAB_AAP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAB_AAP_5_13.mp3"
  },
  {
    "index": "2",
    "set": "AAD_AAT_5",
    "voiced": "D",
    "voiceless": "T",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAD_AAT_5_18.mp3"
  },
  {
    "index": "3",
    "set": "AAG_AAK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAG_AAK_3_12.mp3"
  },
  {
    "index": "4",
    "set": "AHB_AHP_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHB_AHP_1_13.mp3"
  },
  {
    "index": "5",
    "set": "AHD_AHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHD_AHT_1_17.mp3"
  },
  {
    "index": "6",
    "set": "AHG_AHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHG_AHK_3_15.mp3"
  },
  {
    "index": "7",
    "set": "IHB_IHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHB_IHP_5_16.mp3"
  },
  {
    "index": "8",
    "set": "IHD_IHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHD_IHT_1_18.mp3"
  },
  {
    "index": "9",
    "set": "IHG_IHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHG_IHK_3_19.mp3"
  },
  {
    "index": "10",
    "set": "UHB_UHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHB_UHP_5_13.mp3"
  },
  {
    "index": "11",
    "set": "UHD_UHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHD_UHT_1_16.mp3"
  },
  {
    "index": "12",
    "set": "UHG_UHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHG_UHK_3_17.mp3"
  },
  {
    "index": "13",
    "set": "AAB_AAP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAB_AAP_5_7.mp3"
  },
  {
    "index": "14",
    "set": "AAD_AAT_5",
    "voiced": "D",
    "voiceless": "T",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAD_AAT_5_12.mp3"
  },
  {
    "index": "15",
    "set": "AAG_AAK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "6",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAG_AAK_3_6.mp3"
  },
  {
    "index": "16",
    "set": "AHB_AHP_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHB_AHP_1_7.mp3"
  },
  {
    "index": "17",
    "set": "AHD_AHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHD_AHT_1_11.mp3"
  },
  {
    "index": "18",
    "set": "AHG_AHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHG_AHK_3_9.mp3"
  },
  {
    "index": "19",
    "set": "IHB_IHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHB_IHP_5_10.mp3"
  },
  {
    "index": "20",
    "set": "IHD_IHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHD_IHT_1_12.mp3"
  },
  {
    "index": "21",
    "set": "IHG_IHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHG_IHK_3_13.mp3"
  },
  {
    "index": "22",
    "set": "UHB_UHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHB_UHP_5_7.mp3"
  },
  {
    "index": "23",
    "set": "UHD_UHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHD_UHT_1_10.mp3"
  },
  {
    "index": "24",
    "set": "UHG_UHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHG_UHK_3_11.mp3"
  },
  {
    "index": "25",
    "set": "AAB_AAP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAB_AAP_5_9.mp3"
  },
  {
    "index": "26",
    "set": "AAD_AAT_5",
    "voiced": "D",
    "voiceless": "T",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAD_AAT_5_14.mp3"
  },
  {
    "index": "27",
    "set": "AAG_AAK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAG_AAK_3_8.mp3"
  },
  {
    "index": "28",
    "set": "AHB_AHP_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHB_AHP_1_9.mp3"
  },
  {
    "index": "29",
    "set": "AHD_AHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHD_AHT_1_13.mp3"
  },
  {
    "index": "30",
    "set": "AHG_AHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHG_AHK_3_11.mp3"
  },
  {
    "index": "31",
    "set": "IHB_IHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHB_IHP_5_12.mp3"
  },
  {
    "index": "32",
    "set": "IHD_IHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHD_IHT_1_14.mp3"
  },
  {
    "index": "33",
    "set": "IHG_IHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHG_IHK_3_15.mp3"
  },
  {
    "index": "34",
    "set": "UHB_UHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHB_UHP_5_9.mp3"
  },
  {
    "index": "35",
    "set": "UHD_UHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHD_UHT_1_12.mp3"
  },
  {
    "index": "36",
    "set": "UHG_UHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHG_UHK_3_13.mp3"
  },
  {
    "index": "37",
    "set": "AAB_AAP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAB_AAP_5_11.mp3"
  },
  {
    "index": "38",
    "set": "AAD_AAT_5",
    "voiced": "D",
    "voiceless": "T",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAD_AAT_5_16.mp3"
  },
  {
    "index": "39",
    "set": "AAG_AAK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAG_AAK_3_10.mp3"
  },
  {
    "index": "40",
    "set": "AHB_AHP_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHB_AHP_1_11.mp3"
  },
  {
    "index": "41",
    "set": "AHD_AHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHD_AHT_1_15.mp3"
  },
  {
    "index": "42",
    "set": "AHG_AHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHG_AHK_3_13.mp3"
  },
  {
    "index": "43",
    "set": "IHB_IHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHB_IHP_5_14.mp3"
  },
  {
    "index": "44",
    "set": "IHD_IHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHD_IHT_1_16.mp3"
  },
  {
    "index": "45",
    "set": "IHG_IHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHG_IHK_3_17.mp3"
  },
  {
    "index": "46",
    "set": "UHB_UHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHB_UHP_5_11.mp3"
  },
  {
    "index": "47",
    "set": "UHD_UHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHD_UHT_1_14.mp3"
  },
  {
    "index": "48",
    "set": "UHG_UHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHG_UHK_3_15.mp3"
  },
  {
    "index": "49",
    "set": "AAB_AAP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAB_AAP_5_15.mp3"
  },
  {
    "index": "50",
    "set": "AAD_AAT_5",
    "voiced": "D",
    "voiceless": "T",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAD_AAT_5_20.mp3"
  },
  {
    "index": "51",
    "set": "AAG_AAK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAG_AAK_3_14.mp3"
  },
  {
    "index": "52",
    "set": "AHB_AHP_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHB_AHP_1_15.mp3"
  },
  {
    "index": "53",
    "set": "AHD_AHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHD_AHT_1_19.mp3"
  },
  {
    "index": "54",
    "set": "AHG_AHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHG_AHK_3_17.mp3"
  },
  {
    "index": "55",
    "set": "IHB_IHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHB_IHP_5_18.mp3"
  },
  {
    "index": "56",
    "set": "IHD_IHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHD_IHT_1_20.mp3"
  },
  {
    "index": "57",
    "set": "IHG_IHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHG_IHK_3_21.mp3"
  },
  {
    "index": "58",
    "set": "UHB_UHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHB_UHP_5_15.mp3"
  },
  {
    "index": "59",
    "set": "UHD_UHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHD_UHT_1_18.mp3"
  },
  {
    "index": "60",
    "set": "UHG_UHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHG_UHK_3_19.mp3"
  },
  {
    "index": "61",
    "set": "AAB_AAP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAB_AAP_5_17.mp3"
  },
  {
    "index": "62",
    "set": "AAD_AAT_5",
    "voiced": "D",
    "voiceless": "T",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAD_AAT_5_22.mp3"
  },
  {
    "index": "63",
    "set": "AAG_AAK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAG_AAK_3_16.mp3"
  },
  {
    "index": "64",
    "set": "AHB_AHP_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHB_AHP_1_17.mp3"
  },
  {
    "index": "65",
    "set": "AHD_AHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHD_AHT_1_21.mp3"
  },
  {
    "index": "66",
    "set": "AHG_AHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHG_AHK_3_19.mp3"
  },
  {
    "index": "67",
    "set": "IHB_IHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHB_IHP_5_20.mp3"
  },
  {
    "index": "68",
    "set": "IHD_IHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHD_IHT_1_22.mp3"
  },
  {
    "index": "69",
    "set": "IHG_IHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHG_IHK_3_23.mp3"
  },
  {
    "index": "70",
    "set": "UHB_UHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHB_UHP_5_17.mp3"
  },
  {
    "index": "71",
    "set": "UHD_UHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHD_UHT_1_20.mp3"
  },
  {
    "index": "72",
    "set": "UHG_UHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHG_UHK_3_21.mp3"
  },
  {
    "index": "73",
    "set": "AAB_AAP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAB_AAP_5_19.mp3"
  },
  {
    "index": "74",
    "set": "AAD_AAT_5",
    "voiced": "D",
    "voiceless": "T",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAD_AAT_5_24.mp3"
  },
  {
    "index": "75",
    "set": "AAG_AAK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AAG_AAK_3_18.mp3"
  },
  {
    "index": "76",
    "set": "AHB_AHP_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHB_AHP_1_19.mp3"
  },
  {
    "index": "77",
    "set": "AHD_AHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHD_AHT_1_23.mp3"
  },
  {
    "index": "78",
    "set": "AHG_AHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "AHG_AHK_3_21.mp3"
  },
  {
    "index": "79",
    "set": "IHB_IHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHB_IHP_5_22.mp3"
  },
  {
    "index": "80",
    "set": "IHD_IHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHD_IHT_1_24.mp3"
  },
  {
    "index": "81",
    "set": "IHG_IHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "IHG_IHK_3_25.mp3"
  },
  {
    "index": "82",
    "set": "UHB_UHP_5",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHB_UHP_5_19.mp3"
  },
  {
    "index": "83",
    "set": "UHD_UHT_1",
    "voiced": "D",
    "voiceless": "T",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHD_UHT_1_22.mp3"
  },
  {
    "index": "84",
    "set": "UHG_UHK_3",
    "voiced": "G",
    "voiceless": "K",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "UHG_UHK_3_23.mp3"
  }
]

var assetPaths = [
  "audio/onset/BAA_PAA_5_23.mp3",
  "audio/onset/BAH_PAH_3_20.mp3",
  "audio/onset/BIH_PIH_1_21.mp3",
  "audio/onset/BUH_PUH_3_17.mp3",
  "audio/onset/DAA_TAA_3_21.mp3",
  "audio/onset/DAH_TAH_3_24.mp3",
  "audio/onset/DIH_TIH_3_20.mp3",
  "audio/onset/DUH_TUH_3_23.mp3",
  "audio/onset/GAA_KAA_5_24.mp3",
  "audio/onset/GAH_KAH_3_18.mp3",
  "audio/onset/GIH_KIH_5_22.mp3",
  "audio/onset/GUH_KUH_3_18.mp3",
  "audio/onset/BAA_PAA_5_17.mp3",
  "audio/onset/BAH_PAH_3_14.mp3",
  "audio/onset/BIH_PIH_1_15.mp3",
  "audio/onset/BUH_PUH_3_11.mp3",
  "audio/onset/DAA_TAA_3_15.mp3",
  "audio/onset/DAH_TAH_3_18.mp3",
  "audio/onset/DIH_TIH_3_14.mp3",
  "audio/onset/DUH_TUH_3_17.mp3",
  "audio/onset/GAA_KAA_5_18.mp3",
  "audio/onset/GAH_KAH_3_12.mp3",
  "audio/onset/GIH_KIH_5_16.mp3",
  "audio/onset/GUH_KUH_3_12.mp3",
  "audio/onset/BAA_PAA_5_19.mp3",
  "audio/onset/BAH_PAH_3_16.mp3",
  "audio/onset/BIH_PIH_1_17.mp3",
  "audio/onset/BUH_PUH_3_13.mp3",
  "audio/onset/DAA_TAA_3_17.mp3",
  "audio/onset/DAH_TAH_3_20.mp3",
  "audio/onset/DIH_TIH_3_16.mp3",
  "audio/onset/DUH_TUH_3_19.mp3",
  "audio/onset/GAA_KAA_5_20.mp3",
  "audio/onset/GAH_KAH_3_14.mp3",
  "audio/onset/GIH_KIH_5_18.mp3",
  "audio/onset/GUH_KUH_3_14.mp3",
  "audio/onset/BAA_PAA_5_21.mp3",
  "audio/onset/BAH_PAH_3_18.mp3",
  "audio/onset/BIH_PIH_1_19.mp3",
  "audio/onset/BUH_PUH_3_15.mp3",
  "audio/onset/DAA_TAA_3_19.mp3",
  "audio/onset/DAH_TAH_3_22.mp3",
  "audio/onset/DIH_TIH_3_18.mp3",
  "audio/onset/DUH_TUH_3_21.mp3",
  "audio/onset/GAA_KAA_5_22.mp3",
  "audio/onset/GAH_KAH_3_16.mp3",
  "audio/onset/GIH_KIH_5_20.mp3",
  "audio/onset/GUH_KUH_3_16.mp3",
  "audio/onset/BAA_PAA_5_25.mp3",
  "audio/onset/BAH_PAH_3_22.mp3",
  "audio/onset/BIH_PIH_1_23.mp3",
  "audio/onset/BUH_PUH_3_19.mp3",
  "audio/onset/DAA_TAA_3_23.mp3",
  "audio/onset/DAH_TAH_3_26.mp3",
  "audio/onset/DIH_TIH_3_22.mp3",
  "audio/onset/DUH_TUH_3_25.mp3",
  "audio/onset/GAA_KAA_5_26.mp3",
  "audio/onset/GAH_KAH_3_20.mp3",
  "audio/onset/GIH_KIH_5_24.mp3",
  "audio/onset/GUH_KUH_3_20.mp3",
  "audio/onset/BAA_PAA_5_27.mp3",
  "audio/onset/BAH_PAH_3_24.mp3",
  "audio/onset/BIH_PIH_1_25.mp3",
  "audio/onset/BUH_PUH_3_21.mp3",
  "audio/onset/DAA_TAA_3_25.mp3",
  "audio/onset/DAH_TAH_3_28.mp3",
  "audio/onset/DIH_TIH_3_24.mp3",
  "audio/onset/DUH_TUH_3_27.mp3",
  "audio/onset/GAA_KAA_5_28.mp3",
  "audio/onset/GAH_KAH_3_22.mp3",
  "audio/onset/GIH_KIH_5_26.mp3",
  "audio/onset/GUH_KUH_3_22.mp3",
  "audio/onset/BAA_PAA_5_29.mp3",
  "audio/onset/BAH_PAH_3_26.mp3",
  "audio/onset/BIH_PIH_1_27.mp3",
  "audio/onset/BUH_PUH_3_23.mp3",
  "audio/onset/DAA_TAA_3_27.mp3",
  "audio/onset/DAH_TAH_3_30.mp3",
  "audio/onset/DIH_TIH_3_26.mp3",
  "audio/onset/DUH_TUH_3_29.mp3",
  "audio/onset/GAA_KAA_5_30.mp3",
  "audio/onset/GAH_KAH_3_24.mp3",
  "audio/onset/GIH_KIH_5_28.mp3",
  "audio/onset/GUH_KUH_3_24.mp3",
  "audio/coda/AAB_AAP_5_13.mp3",
  "audio/coda/AAD_AAT_5_18.mp3",
  "audio/coda/AAG_AAK_3_12.mp3",
  "audio/coda/AHB_AHP_1_13.mp3",
  "audio/coda/AHD_AHT_1_17.mp3",
  "audio/coda/AHG_AHK_3_15.mp3",
  "audio/coda/IHB_IHP_5_16.mp3",
  "audio/coda/IHD_IHT_1_18.mp3",
  "audio/coda/IHG_IHK_3_19.mp3",
  "audio/coda/UHB_UHP_5_13.mp3",
  "audio/coda/UHD_UHT_1_16.mp3",
  "audio/coda/UHG_UHK_3_17.mp3",
  "audio/coda/AAB_AAP_5_7.mp3",
  "audio/coda/AAD_AAT_5_12.mp3",
  "audio/coda/AAG_AAK_3_6.mp3",
  "audio/coda/AHB_AHP_1_7.mp3",
  "audio/coda/AHD_AHT_1_11.mp3",
  "audio/coda/AHG_AHK_3_9.mp3",
  "audio/coda/IHB_IHP_5_10.mp3",
  "audio/coda/IHD_IHT_1_12.mp3",
  "audio/coda/IHG_IHK_3_13.mp3",
  "audio/coda/UHB_UHP_5_7.mp3",
  "audio/coda/UHD_UHT_1_10.mp3",
  "audio/coda/UHG_UHK_3_11.mp3",
  "audio/coda/AAB_AAP_5_9.mp3",
  "audio/coda/AAD_AAT_5_14.mp3",
  "audio/coda/AAG_AAK_3_8.mp3",
  "audio/coda/AHB_AHP_1_9.mp3",
  "audio/coda/AHD_AHT_1_13.mp3",
  "audio/coda/AHG_AHK_3_11.mp3",
  "audio/coda/IHB_IHP_5_12.mp3",
  "audio/coda/IHD_IHT_1_14.mp3",
  "audio/coda/IHG_IHK_3_15.mp3",
  "audio/coda/UHB_UHP_5_9.mp3",
  "audio/coda/UHD_UHT_1_12.mp3",
  "audio/coda/UHG_UHK_3_13.mp3",
  "audio/coda/AAB_AAP_5_11.mp3",
  "audio/coda/AAD_AAT_5_16.mp3",
  "audio/coda/AAG_AAK_3_10.mp3",
  "audio/coda/AHB_AHP_1_11.mp3",
  "audio/coda/AHD_AHT_1_15.mp3",
  "audio/coda/AHG_AHK_3_13.mp3",
  "audio/coda/IHB_IHP_5_14.mp3",
  "audio/coda/IHD_IHT_1_16.mp3",
  "audio/coda/IHG_IHK_3_17.mp3",
  "audio/coda/UHB_UHP_5_11.mp3",
  "audio/coda/UHD_UHT_1_14.mp3",
  "audio/coda/UHG_UHK_3_15.mp3",
  "audio/coda/AAB_AAP_5_15.mp3",
  "audio/coda/AAD_AAT_5_20.mp3",
  "audio/coda/AAG_AAK_3_14.mp3",
  "audio/coda/AHB_AHP_1_15.mp3",
  "audio/coda/AHD_AHT_1_19.mp3",
  "audio/coda/AHG_AHK_3_17.mp3",
  "audio/coda/IHB_IHP_5_18.mp3",
  "audio/coda/IHD_IHT_1_20.mp3",
  "audio/coda/IHG_IHK_3_21.mp3",
  "audio/coda/UHB_UHP_5_15.mp3",
  "audio/coda/UHD_UHT_1_18.mp3",
  "audio/coda/UHG_UHK_3_19.mp3",
  "audio/coda/AAB_AAP_5_17.mp3",
  "audio/coda/AAD_AAT_5_22.mp3",
  "audio/coda/AAG_AAK_3_16.mp3",
  "audio/coda/AHB_AHP_1_17.mp3",
  "audio/coda/AHD_AHT_1_21.mp3",
  "audio/coda/AHG_AHK_3_19.mp3",
  "audio/coda/IHB_IHP_5_20.mp3",
  "audio/coda/IHD_IHT_1_22.mp3",
  "audio/coda/IHG_IHK_3_23.mp3",
  "audio/coda/UHB_UHP_5_17.mp3",
  "audio/coda/UHD_UHT_1_20.mp3",
  "audio/coda/UHG_UHK_3_21.mp3",
  "audio/coda/AAB_AAP_5_19.mp3",
  "audio/coda/AAD_AAT_5_24.mp3",
  "audio/coda/AAG_AAK_3_18.mp3",
  "audio/coda/AHB_AHP_1_19.mp3",
  "audio/coda/AHD_AHT_1_23.mp3",
  "audio/coda/AHG_AHK_3_21.mp3",
  "audio/coda/IHB_IHP_5_22.mp3",
  "audio/coda/IHD_IHT_1_24.mp3",
  "audio/coda/IHG_IHK_3_25.mp3",
  "audio/coda/UHB_UHP_5_19.mp3",
  "audio/coda/UHD_UHT_1_22.mp3",
  "audio/coda/UHG_UHK_3_23.mp3"
]