
var word_trial_stimuli = [
  {
    "index": "1",
    "set": "Balloon_Palloon_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Balloon_Palloon_3_12.mp3"
  },
  {
    "index": "2",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_13.mp3"
  },
  {
    "index": "3",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_12.mp3"
  },
  {
    "index": "4",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_21.mp3"
  },
  {
    "index": "5",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_24.mp3"
  },
  {
    "index": "6",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_19.mp3"
  },
  {
    "index": "7",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_18.mp3"
  },
  {
    "index": "8",
    "set": "Billionaire_Pillionaire_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billionaire_Pillionaire_3_12.mp3"
  },
  {
    "index": "9",
    "set": "Boom_Poom_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boom_Poom_1_16.mp3"
  },
  {
    "index": "10",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_16.mp3"
  },
  {
    "index": "11",
    "set": "Brown_Prown_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brown_Prown_3_11.mp3"
  },
  {
    "index": "12",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_16.mp3"
  },
  {
    "index": "13",
    "set": "Baloney_Paloney_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Baloney_Paloney_1_11.mp3"
  },
  {
    "index": "14",
    "set": "Barallel_Parallel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barallel_Parallel_3_18.mp3"
  },
  {
    "index": "15",
    "set": "Barely_Parely_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barely_Parely_1_11.mp3"
  },
  {
    "index": "16",
    "set": "Barlor_Parlor_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barlor_Parlor_3_22.mp3"
  },
  {
    "index": "17",
    "set": "Barren_Parren_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barren_Parren_3_13.mp3"
  },
  {
    "index": "18",
    "set": "Belly_Pelly_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Belly_Pelly_3_20.mp3"
  },
  {
    "index": "19",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_11.mp3"
  },
  {
    "index": "20",
    "set": "Biannual_Piannual_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Biannual_Piannual_3_8.mp3"
  },
  {
    "index": "21",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_21.mp3"
  },
  {
    "index": "22",
    "set": "Blanner_Planner_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blanner_Planner_3_23.mp3"
  },
  {
    "index": "23",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_19.mp3"
  },
  {
    "index": "24",
    "set": "Blue_Plue_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blue_Plue_3_17.mp3"
  },
  {
    "index": "25",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_18.mp3"
  },
  {
    "index": "26",
    "set": "Boil_Poil_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boil_Poil_1_15.mp3"
  },
  {
    "index": "27",
    "set": "Bollen_Pollen_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bollen_Pollen_3_24.mp3"
  },
  {
    "index": "28",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_22.mp3"
  },
  {
    "index": "29",
    "set": "Brain_Prain_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brain_Prain_3_15.mp3"
  },
  {
    "index": "30",
    "set": "Brayer_Prayer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brayer_Prayer_1_20.mp3"
  },
  {
    "index": "31",
    "set": "Breliminary_Preliminary_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_1_24.mp3"
  },
  {
    "index": "32",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_19.mp3"
  },
  {
    "index": "33",
    "set": "Brewery_Prewery_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brewery_Prewery_1_15.mp3"
  },
  {
    "index": "34",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_23.mp3"
  },
  {
    "index": "35",
    "set": "Brior_Prior_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brior_Prior_3_22.mp3"
  },
  {
    "index": "36",
    "set": "Browl_Prowl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_3_18.mp3"
  },
  {
    "index": "37",
    "set": "Bry_Pry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bry_Pry_1_22.mp3"
  },
  {
    "index": "38",
    "set": "Burial_Purial_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burial_Purial_1_18.mp3"
  },
  {
    "index": "39",
    "set": "Burrow_Purrow_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burrow_Purrow_3_13.mp3"
  },
  {
    "index": "40",
    "set": "Bylon_Pylon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_1_17.mp3"
  },
  {
    "index": "41",
    "set": "Balloon_Palloon_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Balloon_Palloon_3_8.mp3"
  },
  {
    "index": "42",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_9.mp3"
  },
  {
    "index": "43",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_8.mp3"
  },
  {
    "index": "44",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_17.mp3"
  },
  {
    "index": "45",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_20.mp3"
  },
  {
    "index": "46",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_15.mp3"
  },
  {
    "index": "47",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_14.mp3"
  },
  {
    "index": "48",
    "set": "Billionaire_Pillionaire_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billionaire_Pillionaire_3_8.mp3"
  },
  {
    "index": "49",
    "set": "Boom_Poom_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boom_Poom_1_12.mp3"
  },
  {
    "index": "50",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_12.mp3"
  },
  {
    "index": "51",
    "set": "Brown_Prown_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brown_Prown_3_7.mp3"
  },
  {
    "index": "52",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_12.mp3"
  },
  {
    "index": "53",
    "set": "Baloney_Paloney_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Baloney_Paloney_1_7.mp3"
  },
  {
    "index": "54",
    "set": "Barallel_Parallel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barallel_Parallel_3_14.mp3"
  },
  {
    "index": "55",
    "set": "Barely_Parely_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barely_Parely_1_7.mp3"
  },
  {
    "index": "56",
    "set": "Barlor_Parlor_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barlor_Parlor_3_18.mp3"
  },
  {
    "index": "57",
    "set": "Barren_Parren_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barren_Parren_3_9.mp3"
  },
  {
    "index": "58",
    "set": "Belly_Pelly_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Belly_Pelly_3_16.mp3"
  },
  {
    "index": "59",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_7.mp3"
  },
  {
    "index": "60",
    "set": "Biannual_Piannual_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "4",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Biannual_Piannual_3_4.mp3"
  },
  {
    "index": "61",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_17.mp3"
  },
  {
    "index": "62",
    "set": "Blanner_Planner_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blanner_Planner_3_19.mp3"
  },
  {
    "index": "63",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_15.mp3"
  },
  {
    "index": "64",
    "set": "Blue_Plue_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blue_Plue_3_13.mp3"
  },
  {
    "index": "65",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_14.mp3"
  },
  {
    "index": "66",
    "set": "Boil_Poil_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boil_Poil_1_11.mp3"
  },
  {
    "index": "67",
    "set": "Bollen_Pollen_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bollen_Pollen_3_20.mp3"
  },
  {
    "index": "68",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_18.mp3"
  },
  {
    "index": "69",
    "set": "Brain_Prain_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brain_Prain_3_11.mp3"
  },
  {
    "index": "70",
    "set": "Brayer_Prayer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brayer_Prayer_1_16.mp3"
  },
  {
    "index": "71",
    "set": "Breliminary_Preliminary_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_1_20.mp3"
  },
  {
    "index": "72",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_15.mp3"
  },
  {
    "index": "73",
    "set": "Brewery_Prewery_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brewery_Prewery_1_11.mp3"
  },
  {
    "index": "74",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_19.mp3"
  },
  {
    "index": "75",
    "set": "Brior_Prior_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brior_Prior_3_18.mp3"
  },
  {
    "index": "76",
    "set": "Browl_Prowl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_3_14.mp3"
  },
  {
    "index": "77",
    "set": "Bry_Pry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bry_Pry_1_18.mp3"
  },
  {
    "index": "78",
    "set": "Burial_Purial_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burial_Purial_1_14.mp3"
  },
  {
    "index": "79",
    "set": "Burrow_Purrow_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burrow_Purrow_3_9.mp3"
  },
  {
    "index": "80",
    "set": "Bylon_Pylon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_1_13.mp3"
  },
  {
    "index": "81",
    "set": "Balloon_Palloon_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Balloon_Palloon_3_10.mp3"
  },
  {
    "index": "82",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_11.mp3"
  },
  {
    "index": "83",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_10.mp3"
  },
  {
    "index": "84",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_19.mp3"
  },
  {
    "index": "85",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_22.mp3"
  },
  {
    "index": "86",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_17.mp3"
  },
  {
    "index": "87",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_16.mp3"
  },
  {
    "index": "88",
    "set": "Billionaire_Pillionaire_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billionaire_Pillionaire_3_10.mp3"
  },
  {
    "index": "89",
    "set": "Boom_Poom_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boom_Poom_1_14.mp3"
  },
  {
    "index": "90",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_14.mp3"
  },
  {
    "index": "91",
    "set": "Brown_Prown_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brown_Prown_3_9.mp3"
  },
  {
    "index": "92",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_14.mp3"
  },
  {
    "index": "93",
    "set": "Baloney_Paloney_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Baloney_Paloney_1_9.mp3"
  },
  {
    "index": "94",
    "set": "Barallel_Parallel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barallel_Parallel_3_16.mp3"
  },
  {
    "index": "95",
    "set": "Barely_Parely_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barely_Parely_1_9.mp3"
  },
  {
    "index": "96",
    "set": "Barlor_Parlor_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barlor_Parlor_3_20.mp3"
  },
  {
    "index": "97",
    "set": "Barren_Parren_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barren_Parren_3_11.mp3"
  },
  {
    "index": "98",
    "set": "Belly_Pelly_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Belly_Pelly_3_18.mp3"
  },
  {
    "index": "99",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_9.mp3"
  },
  {
    "index": "100",
    "set": "Biannual_Piannual_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "6",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Biannual_Piannual_3_6.mp3"
  },
  {
    "index": "101",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_19.mp3"
  },
  {
    "index": "102",
    "set": "Blanner_Planner_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blanner_Planner_3_21.mp3"
  },
  {
    "index": "103",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_17.mp3"
  },
  {
    "index": "104",
    "set": "Blue_Plue_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blue_Plue_3_15.mp3"
  },
  {
    "index": "105",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_16.mp3"
  },
  {
    "index": "106",
    "set": "Boil_Poil_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boil_Poil_1_13.mp3"
  },
  {
    "index": "107",
    "set": "Bollen_Pollen_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bollen_Pollen_3_22.mp3"
  },
  {
    "index": "108",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_20.mp3"
  },
  {
    "index": "109",
    "set": "Brain_Prain_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brain_Prain_3_13.mp3"
  },
  {
    "index": "110",
    "set": "Brayer_Prayer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brayer_Prayer_1_18.mp3"
  },
  {
    "index": "111",
    "set": "Breliminary_Preliminary_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_1_22.mp3"
  },
  {
    "index": "112",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_17.mp3"
  },
  {
    "index": "113",
    "set": "Brewery_Prewery_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brewery_Prewery_1_13.mp3"
  },
  {
    "index": "114",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_21.mp3"
  },
  {
    "index": "115",
    "set": "Brior_Prior_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brior_Prior_3_20.mp3"
  },
  {
    "index": "116",
    "set": "Browl_Prowl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_3_16.mp3"
  },
  {
    "index": "117",
    "set": "Bry_Pry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bry_Pry_1_20.mp3"
  },
  {
    "index": "118",
    "set": "Burial_Purial_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burial_Purial_1_16.mp3"
  },
  {
    "index": "119",
    "set": "Burrow_Purrow_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burrow_Purrow_3_11.mp3"
  },
  {
    "index": "120",
    "set": "Bylon_Pylon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_1_15.mp3"
  },
  {
    "index": "121",
    "set": "Balloon_Palloon_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Balloon_Palloon_3_14.mp3"
  },
  {
    "index": "122",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_15.mp3"
  },
  {
    "index": "123",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_14.mp3"
  },
  {
    "index": "124",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_23.mp3"
  },
  {
    "index": "125",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_26.mp3"
  },
  {
    "index": "126",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_21.mp3"
  },
  {
    "index": "127",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_20.mp3"
  },
  {
    "index": "128",
    "set": "Billionaire_Pillionaire_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billionaire_Pillionaire_3_14.mp3"
  },
  {
    "index": "129",
    "set": "Boom_Poom_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boom_Poom_1_18.mp3"
  },
  {
    "index": "130",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_18.mp3"
  },
  {
    "index": "131",
    "set": "Brown_Prown_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brown_Prown_3_13.mp3"
  },
  {
    "index": "132",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_18.mp3"
  },
  {
    "index": "133",
    "set": "Baloney_Paloney_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Baloney_Paloney_1_13.mp3"
  },
  {
    "index": "134",
    "set": "Barallel_Parallel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barallel_Parallel_3_20.mp3"
  },
  {
    "index": "135",
    "set": "Barely_Parely_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barely_Parely_1_13.mp3"
  },
  {
    "index": "136",
    "set": "Barlor_Parlor_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barlor_Parlor_3_24.mp3"
  },
  {
    "index": "137",
    "set": "Barren_Parren_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barren_Parren_3_15.mp3"
  },
  {
    "index": "138",
    "set": "Belly_Pelly_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Belly_Pelly_3_22.mp3"
  },
  {
    "index": "139",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_13.mp3"
  },
  {
    "index": "140",
    "set": "Biannual_Piannual_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Biannual_Piannual_3_10.mp3"
  },
  {
    "index": "141",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_23.mp3"
  },
  {
    "index": "142",
    "set": "Blanner_Planner_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blanner_Planner_3_25.mp3"
  },
  {
    "index": "143",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_21.mp3"
  },
  {
    "index": "144",
    "set": "Blue_Plue_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blue_Plue_3_19.mp3"
  },
  {
    "index": "145",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_20.mp3"
  },
  {
    "index": "146",
    "set": "Boil_Poil_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boil_Poil_1_17.mp3"
  },
  {
    "index": "147",
    "set": "Bollen_Pollen_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bollen_Pollen_3_26.mp3"
  },
  {
    "index": "148",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_24.mp3"
  },
  {
    "index": "149",
    "set": "Brain_Prain_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brain_Prain_3_17.mp3"
  },
  {
    "index": "150",
    "set": "Brayer_Prayer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brayer_Prayer_1_22.mp3"
  },
  {
    "index": "151",
    "set": "Breliminary_Preliminary_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_1_26.mp3"
  },
  {
    "index": "152",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_21.mp3"
  },
  {
    "index": "153",
    "set": "Brewery_Prewery_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brewery_Prewery_1_17.mp3"
  },
  {
    "index": "154",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_25.mp3"
  },
  {
    "index": "155",
    "set": "Brior_Prior_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brior_Prior_3_24.mp3"
  },
  {
    "index": "156",
    "set": "Browl_Prowl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_3_20.mp3"
  },
  {
    "index": "157",
    "set": "Bry_Pry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bry_Pry_1_24.mp3"
  },
  {
    "index": "158",
    "set": "Burial_Purial_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burial_Purial_1_20.mp3"
  },
  {
    "index": "159",
    "set": "Burrow_Purrow_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burrow_Purrow_3_15.mp3"
  },
  {
    "index": "160",
    "set": "Bylon_Pylon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_1_19.mp3"
  },
  {
    "index": "161",
    "set": "Balloon_Palloon_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Balloon_Palloon_3_16.mp3"
  },
  {
    "index": "162",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_17.mp3"
  },
  {
    "index": "163",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_16.mp3"
  },
  {
    "index": "164",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_25.mp3"
  },
  {
    "index": "165",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_28.mp3"
  },
  {
    "index": "166",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_23.mp3"
  },
  {
    "index": "167",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_22.mp3"
  },
  {
    "index": "168",
    "set": "Billionaire_Pillionaire_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billionaire_Pillionaire_3_16.mp3"
  },
  {
    "index": "169",
    "set": "Boom_Poom_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boom_Poom_1_20.mp3"
  },
  {
    "index": "170",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_20.mp3"
  },
  {
    "index": "171",
    "set": "Brown_Prown_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brown_Prown_3_15.mp3"
  },
  {
    "index": "172",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_20.mp3"
  },
  {
    "index": "173",
    "set": "Baloney_Paloney_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Baloney_Paloney_1_15.mp3"
  },
  {
    "index": "174",
    "set": "Barallel_Parallel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barallel_Parallel_3_22.mp3"
  },
  {
    "index": "175",
    "set": "Barely_Parely_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barely_Parely_1_15.mp3"
  },
  {
    "index": "176",
    "set": "Barlor_Parlor_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barlor_Parlor_3_26.mp3"
  },
  {
    "index": "177",
    "set": "Barren_Parren_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barren_Parren_3_17.mp3"
  },
  {
    "index": "178",
    "set": "Belly_Pelly_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Belly_Pelly_3_24.mp3"
  },
  {
    "index": "179",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_15.mp3"
  },
  {
    "index": "180",
    "set": "Biannual_Piannual_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Biannual_Piannual_3_12.mp3"
  },
  {
    "index": "181",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_25.mp3"
  },
  {
    "index": "182",
    "set": "Blanner_Planner_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blanner_Planner_3_27.mp3"
  },
  {
    "index": "183",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_23.mp3"
  },
  {
    "index": "184",
    "set": "Blue_Plue_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blue_Plue_3_21.mp3"
  },
  {
    "index": "185",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_22.mp3"
  },
  {
    "index": "186",
    "set": "Boil_Poil_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Boil_Poil_1_19.mp3"
  },
  {
    "index": "187",
    "set": "Bollen_Pollen_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bollen_Pollen_3_28.mp3"
  },
  {
    "index": "188",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_26.mp3"
  },
  {
    "index": "189",
    "set": "Brain_Prain_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brain_Prain_3_19.mp3"
  },
  {
    "index": "190",
    "set": "Brayer_Prayer_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brayer_Prayer_1_24.mp3"
  },
  {
    "index": "191",
    "set": "Breliminary_Preliminary_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_1_28.mp3"
  },
  {
    "index": "192",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_23.mp3"
  },
  {
    "index": "193",
    "set": "Brewery_Prewery_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brewery_Prewery_1_19.mp3"
  },
  {
    "index": "194",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_27.mp3"
  },
  {
    "index": "195",
    "set": "Brior_Prior_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brior_Prior_3_26.mp3"
  },
  {
    "index": "196",
    "set": "Browl_Prowl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_3_22.mp3"
  },
  {
    "index": "197",
    "set": "Bry_Pry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bry_Pry_1_26.mp3"
  },
  {
    "index": "198",
    "set": "Burial_Purial_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burial_Purial_1_22.mp3"
  },
  {
    "index": "199",
    "set": "Burrow_Purrow_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Burrow_Purrow_3_17.mp3"
  },
  {
    "index": "200",
    "set": "Bylon_Pylon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_1_21.mp3"
  }
]

var nonword_trial_stimuli = [
  {
    "index": "1",
    "set": "balinomy_palinomy_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "balinomy_palinomy_1_23.mp3"
  },
  {
    "index": "2",
    "set": "baln_paln_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "baln_paln_3_20.mp3"
  },
  {
    "index": "3",
    "set": "bamurre_pamurre_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bamurre_pamurre_3_22.mp3"
  },
  {
    "index": "4",
    "set": "bangle_pangle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bangle_pangle_3_24.mp3"
  },
  {
    "index": "5",
    "set": "barema_parema_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barema_parema_3_17.mp3"
  },
  {
    "index": "6",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_19.mp3"
  },
  {
    "index": "7",
    "set": "belammer_pelammer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "belammer_pelammer_3_16.mp3"
  },
  {
    "index": "8",
    "set": "bellon_pellon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bellon_pellon_1_19.mp3"
  },
  {
    "index": "9",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_23.mp3"
  },
  {
    "index": "10",
    "set": "bemmerle_pemmerle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmerle_pemmerle_3_22.mp3"
  },
  {
    "index": "11",
    "set": "benlow_penlow_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "benlow_penlow_1_18.mp3"
  },
  {
    "index": "12",
    "set": "bennim_pennim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bennim_pennim_3_21.mp3"
  },
  {
    "index": "13",
    "set": "bim_pim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bim_pim_3_16.mp3"
  },
  {
    "index": "14",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_24.mp3"
  },
  {
    "index": "15",
    "set": "binneran_pinneran_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "binneran_pinneran_1_16.mp3"
  },
  {
    "index": "16",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_15.mp3"
  },
  {
    "index": "17",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_15.mp3"
  },
  {
    "index": "18",
    "set": "brynon_prynon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "brynon_prynon_1_22.mp3"
  },
  {
    "index": "19",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_23.mp3"
  },
  {
    "index": "20",
    "set": "Bewry_Pewry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bewry_Pewry_1_18.mp3"
  },
  {
    "index": "21",
    "set": "balinomy_palinomy_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "balinomy_palinomy_1_19.mp3"
  },
  {
    "index": "22",
    "set": "baln_paln_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "baln_paln_3_16.mp3"
  },
  {
    "index": "23",
    "set": "bamurre_pamurre_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bamurre_pamurre_3_18.mp3"
  },
  {
    "index": "24",
    "set": "bangle_pangle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bangle_pangle_3_20.mp3"
  },
  {
    "index": "25",
    "set": "barema_parema_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barema_parema_3_13.mp3"
  },
  {
    "index": "26",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_15.mp3"
  },
  {
    "index": "27",
    "set": "belammer_pelammer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "belammer_pelammer_3_12.mp3"
  },
  {
    "index": "28",
    "set": "bellon_pellon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bellon_pellon_1_15.mp3"
  },
  {
    "index": "29",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_19.mp3"
  },
  {
    "index": "30",
    "set": "bemmerle_pemmerle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmerle_pemmerle_3_18.mp3"
  },
  {
    "index": "31",
    "set": "benlow_penlow_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "benlow_penlow_1_14.mp3"
  },
  {
    "index": "32",
    "set": "bennim_pennim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bennim_pennim_3_17.mp3"
  },
  {
    "index": "33",
    "set": "bim_pim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bim_pim_3_12.mp3"
  },
  {
    "index": "34",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_20.mp3"
  },
  {
    "index": "35",
    "set": "binneran_pinneran_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "binneran_pinneran_1_12.mp3"
  },
  {
    "index": "36",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_11.mp3"
  },
  {
    "index": "37",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_11.mp3"
  },
  {
    "index": "38",
    "set": "brynon_prynon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "brynon_prynon_1_18.mp3"
  },
  {
    "index": "39",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_19.mp3"
  },
  {
    "index": "40",
    "set": "Bewry_Pewry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bewry_Pewry_1_14.mp3"
  },
  {
    "index": "41",
    "set": "balinomy_palinomy_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "balinomy_palinomy_1_21.mp3"
  },
  {
    "index": "42",
    "set": "baln_paln_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "baln_paln_3_18.mp3"
  },
  {
    "index": "43",
    "set": "bamurre_pamurre_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bamurre_pamurre_3_20.mp3"
  },
  {
    "index": "44",
    "set": "bangle_pangle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bangle_pangle_3_22.mp3"
  },
  {
    "index": "45",
    "set": "barema_parema_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barema_parema_3_15.mp3"
  },
  {
    "index": "46",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_17.mp3"
  },
  {
    "index": "47",
    "set": "belammer_pelammer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "belammer_pelammer_3_14.mp3"
  },
  {
    "index": "48",
    "set": "bellon_pellon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bellon_pellon_1_17.mp3"
  },
  {
    "index": "49",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_21.mp3"
  },
  {
    "index": "50",
    "set": "bemmerle_pemmerle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmerle_pemmerle_3_20.mp3"
  },
  {
    "index": "51",
    "set": "benlow_penlow_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "benlow_penlow_1_16.mp3"
  },
  {
    "index": "52",
    "set": "bennim_pennim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bennim_pennim_3_19.mp3"
  },
  {
    "index": "53",
    "set": "bim_pim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bim_pim_3_14.mp3"
  },
  {
    "index": "54",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_22.mp3"
  },
  {
    "index": "55",
    "set": "binneran_pinneran_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "binneran_pinneran_1_14.mp3"
  },
  {
    "index": "56",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_13.mp3"
  },
  {
    "index": "57",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_13.mp3"
  },
  {
    "index": "58",
    "set": "brynon_prynon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "brynon_prynon_1_20.mp3"
  },
  {
    "index": "59",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_21.mp3"
  },
  {
    "index": "60",
    "set": "Bewry_Pewry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bewry_Pewry_1_16.mp3"
  },
  {
    "index": "61",
    "set": "balinomy_palinomy_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "balinomy_palinomy_1_25.mp3"
  },
  {
    "index": "62",
    "set": "baln_paln_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "baln_paln_3_22.mp3"
  },
  {
    "index": "63",
    "set": "bamurre_pamurre_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bamurre_pamurre_3_24.mp3"
  },
  {
    "index": "64",
    "set": "bangle_pangle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bangle_pangle_3_26.mp3"
  },
  {
    "index": "65",
    "set": "barema_parema_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barema_parema_3_19.mp3"
  },
  {
    "index": "66",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_21.mp3"
  },
  {
    "index": "67",
    "set": "belammer_pelammer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "belammer_pelammer_3_18.mp3"
  },
  {
    "index": "68",
    "set": "bellon_pellon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bellon_pellon_1_21.mp3"
  },
  {
    "index": "69",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_25.mp3"
  },
  {
    "index": "70",
    "set": "bemmerle_pemmerle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmerle_pemmerle_3_24.mp3"
  },
  {
    "index": "71",
    "set": "benlow_penlow_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "benlow_penlow_1_20.mp3"
  },
  {
    "index": "72",
    "set": "bennim_pennim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bennim_pennim_3_23.mp3"
  },
  {
    "index": "73",
    "set": "bim_pim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bim_pim_3_18.mp3"
  },
  {
    "index": "74",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_26.mp3"
  },
  {
    "index": "75",
    "set": "binneran_pinneran_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "binneran_pinneran_1_18.mp3"
  },
  {
    "index": "76",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_17.mp3"
  },
  {
    "index": "77",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_17.mp3"
  },
  {
    "index": "78",
    "set": "brynon_prynon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "brynon_prynon_1_24.mp3"
  },
  {
    "index": "79",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_25.mp3"
  },
  {
    "index": "80",
    "set": "Bewry_Pewry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bewry_Pewry_1_20.mp3"
  },
  {
    "index": "81",
    "set": "balinomy_palinomy_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "balinomy_palinomy_1_27.mp3"
  },
  {
    "index": "82",
    "set": "baln_paln_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "baln_paln_3_24.mp3"
  },
  {
    "index": "83",
    "set": "bamurre_pamurre_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bamurre_pamurre_3_26.mp3"
  },
  {
    "index": "84",
    "set": "bangle_pangle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bangle_pangle_3_28.mp3"
  },
  {
    "index": "85",
    "set": "barema_parema_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barema_parema_3_21.mp3"
  },
  {
    "index": "86",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_23.mp3"
  },
  {
    "index": "87",
    "set": "belammer_pelammer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "belammer_pelammer_3_20.mp3"
  },
  {
    "index": "88",
    "set": "bellon_pellon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bellon_pellon_1_23.mp3"
  },
  {
    "index": "89",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_27.mp3"
  },
  {
    "index": "90",
    "set": "bemmerle_pemmerle_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmerle_pemmerle_3_26.mp3"
  },
  {
    "index": "91",
    "set": "benlow_penlow_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "benlow_penlow_1_22.mp3"
  },
  {
    "index": "92",
    "set": "bennim_pennim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bennim_pennim_3_25.mp3"
  },
  {
    "index": "93",
    "set": "bim_pim_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bim_pim_3_20.mp3"
  },
  {
    "index": "94",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_28.mp3"
  },
  {
    "index": "95",
    "set": "binneran_pinneran_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "binneran_pinneran_1_20.mp3"
  },
  {
    "index": "96",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_19.mp3"
  },
  {
    "index": "97",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_19.mp3"
  },
  {
    "index": "98",
    "set": "brynon_prynon_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "brynon_prynon_1_26.mp3"
  },
  {
    "index": "99",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_27.mp3"
  },
  {
    "index": "100",
    "set": "Bewry_Pewry_1",
    "voiced": "B",
    "voiceless": "P",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bewry_Pewry_1_22.mp3"
  }
]

var assetPaths = [
  "audio/word/Balloon_Palloon_3_12.mp3",
  "audio/word/Banana_Panana_3_13.mp3",
  "audio/word/Barn_Parn_1_12.mp3",
  "audio/word/Bawn_Pawn_3_21.mp3",
  "audio/word/Beninsula_Peninsula_3_24.mp3",
  "audio/word/Berform_Perform_3_19.mp3",
  "audio/word/Billion_Pillion_3_18.mp3",
  "audio/word/Billionaire_Pillionaire_3_12.mp3",
  "audio/word/Boom_Poom_1_16.mp3",
  "audio/word/Brime_Prime_1_16.mp3",
  "audio/word/Brown_Prown_3_11.mp3",
  "audio/word/Ballerina_Pallerina_1_16.mp3",
  "audio/word/Baloney_Paloney_1_11.mp3",
  "audio/word/Barallel_Parallel_3_18.mp3",
  "audio/word/Barely_Parely_1_11.mp3",
  "audio/word/Barlor_Parlor_3_22.mp3",
  "audio/word/Barren_Parren_3_13.mp3",
  "audio/word/Belly_Pelly_3_20.mp3",
  "audio/word/Benign_Penign_3_11.mp3",
  "audio/word/Biannual_Piannual_3_8.mp3",
  "audio/word/Bioneer_Pioneer_3_21.mp3",
  "audio/word/Blanner_Planner_3_23.mp3",
  "audio/word/Blea_Plea_3_19.mp3",
  "audio/word/Blue_Plue_3_17.mp3",
  "audio/word/Blyer_Plyer_1_18.mp3",
  "audio/word/Boil_Poil_1_15.mp3",
  "audio/word/Bollen_Pollen_3_24.mp3",
  "audio/word/Bolymer_Polymer_3_22.mp3",
  "audio/word/Brain_Prain_3_15.mp3",
  "audio/word/Brayer_Prayer_1_20.mp3",
  "audio/word/Breliminary_Preliminary_1_24.mp3",
  "audio/word/Bremier_Premier_3_19.mp3",
  "audio/word/Brewery_Prewery_1_15.mp3",
  "audio/word/Brimal_Primal_3_23.mp3",
  "audio/word/Brior_Prior_3_22.mp3",
  "audio/word/Browl_Prowl_3_18.mp3",
  "audio/word/Bry_Pry_1_22.mp3",
  "audio/word/Burial_Purial_1_18.mp3",
  "audio/word/Burrow_Purrow_3_13.mp3",
  "audio/word/Bylon_Pylon_1_17.mp3",
  "audio/word/Balloon_Palloon_3_8.mp3",
  "audio/word/Banana_Panana_3_9.mp3",
  "audio/word/Barn_Parn_1_8.mp3",
  "audio/word/Bawn_Pawn_3_17.mp3",
  "audio/word/Beninsula_Peninsula_3_20.mp3",
  "audio/word/Berform_Perform_3_15.mp3",
  "audio/word/Billion_Pillion_3_14.mp3",
  "audio/word/Billionaire_Pillionaire_3_8.mp3",
  "audio/word/Boom_Poom_1_12.mp3",
  "audio/word/Brime_Prime_1_12.mp3",
  "audio/word/Brown_Prown_3_7.mp3",
  "audio/word/Ballerina_Pallerina_1_12.mp3",
  "audio/word/Baloney_Paloney_1_7.mp3",
  "audio/word/Barallel_Parallel_3_14.mp3",
  "audio/word/Barely_Parely_1_7.mp3",
  "audio/word/Barlor_Parlor_3_18.mp3",
  "audio/word/Barren_Parren_3_9.mp3",
  "audio/word/Belly_Pelly_3_16.mp3",
  "audio/word/Benign_Penign_3_7.mp3",
  "audio/word/Biannual_Piannual_3_4.mp3",
  "audio/word/Bioneer_Pioneer_3_17.mp3",
  "audio/word/Blanner_Planner_3_19.mp3",
  "audio/word/Blea_Plea_3_15.mp3",
  "audio/word/Blue_Plue_3_13.mp3",
  "audio/word/Blyer_Plyer_1_14.mp3",
  "audio/word/Boil_Poil_1_11.mp3",
  "audio/word/Bollen_Pollen_3_20.mp3",
  "audio/word/Bolymer_Polymer_3_18.mp3",
  "audio/word/Brain_Prain_3_11.mp3",
  "audio/word/Brayer_Prayer_1_16.mp3",
  "audio/word/Breliminary_Preliminary_1_20.mp3",
  "audio/word/Bremier_Premier_3_15.mp3",
  "audio/word/Brewery_Prewery_1_11.mp3",
  "audio/word/Brimal_Primal_3_19.mp3",
  "audio/word/Brior_Prior_3_18.mp3",
  "audio/word/Browl_Prowl_3_14.mp3",
  "audio/word/Bry_Pry_1_18.mp3",
  "audio/word/Burial_Purial_1_14.mp3",
  "audio/word/Burrow_Purrow_3_9.mp3",
  "audio/word/Bylon_Pylon_1_13.mp3",
  "audio/word/Balloon_Palloon_3_10.mp3",
  "audio/word/Banana_Panana_3_11.mp3",
  "audio/word/Barn_Parn_1_10.mp3",
  "audio/word/Bawn_Pawn_3_19.mp3",
  "audio/word/Beninsula_Peninsula_3_22.mp3",
  "audio/word/Berform_Perform_3_17.mp3",
  "audio/word/Billion_Pillion_3_16.mp3",
  "audio/word/Billionaire_Pillionaire_3_10.mp3",
  "audio/word/Boom_Poom_1_14.mp3",
  "audio/word/Brime_Prime_1_14.mp3",
  "audio/word/Brown_Prown_3_9.mp3",
  "audio/word/Ballerina_Pallerina_1_14.mp3",
  "audio/word/Baloney_Paloney_1_9.mp3",
  "audio/word/Barallel_Parallel_3_16.mp3",
  "audio/word/Barely_Parely_1_9.mp3",
  "audio/word/Barlor_Parlor_3_20.mp3",
  "audio/word/Barren_Parren_3_11.mp3",
  "audio/word/Belly_Pelly_3_18.mp3",
  "audio/word/Benign_Penign_3_9.mp3",
  "audio/word/Biannual_Piannual_3_6.mp3",
  "audio/word/Bioneer_Pioneer_3_19.mp3",
  "audio/word/Blanner_Planner_3_21.mp3",
  "audio/word/Blea_Plea_3_17.mp3",
  "audio/word/Blue_Plue_3_15.mp3",
  "audio/word/Blyer_Plyer_1_16.mp3",
  "audio/word/Boil_Poil_1_13.mp3",
  "audio/word/Bollen_Pollen_3_22.mp3",
  "audio/word/Bolymer_Polymer_3_20.mp3",
  "audio/word/Brain_Prain_3_13.mp3",
  "audio/word/Brayer_Prayer_1_18.mp3",
  "audio/word/Breliminary_Preliminary_1_22.mp3",
  "audio/word/Bremier_Premier_3_17.mp3",
  "audio/word/Brewery_Prewery_1_13.mp3",
  "audio/word/Brimal_Primal_3_21.mp3",
  "audio/word/Brior_Prior_3_20.mp3",
  "audio/word/Browl_Prowl_3_16.mp3",
  "audio/word/Bry_Pry_1_20.mp3",
  "audio/word/Burial_Purial_1_16.mp3",
  "audio/word/Burrow_Purrow_3_11.mp3",
  "audio/word/Bylon_Pylon_1_15.mp3",
  "audio/word/Balloon_Palloon_3_14.mp3",
  "audio/word/Banana_Panana_3_15.mp3",
  "audio/word/Barn_Parn_1_14.mp3",
  "audio/word/Bawn_Pawn_3_23.mp3",
  "audio/word/Beninsula_Peninsula_3_26.mp3",
  "audio/word/Berform_Perform_3_21.mp3",
  "audio/word/Billion_Pillion_3_20.mp3",
  "audio/word/Billionaire_Pillionaire_3_14.mp3",
  "audio/word/Boom_Poom_1_18.mp3",
  "audio/word/Brime_Prime_1_18.mp3",
  "audio/word/Brown_Prown_3_13.mp3",
  "audio/word/Ballerina_Pallerina_1_18.mp3",
  "audio/word/Baloney_Paloney_1_13.mp3",
  "audio/word/Barallel_Parallel_3_20.mp3",
  "audio/word/Barely_Parely_1_13.mp3",
  "audio/word/Barlor_Parlor_3_24.mp3",
  "audio/word/Barren_Parren_3_15.mp3",
  "audio/word/Belly_Pelly_3_22.mp3",
  "audio/word/Benign_Penign_3_13.mp3",
  "audio/word/Biannual_Piannual_3_10.mp3",
  "audio/word/Bioneer_Pioneer_3_23.mp3",
  "audio/word/Blanner_Planner_3_25.mp3",
  "audio/word/Blea_Plea_3_21.mp3",
  "audio/word/Blue_Plue_3_19.mp3",
  "audio/word/Blyer_Plyer_1_20.mp3",
  "audio/word/Boil_Poil_1_17.mp3",
  "audio/word/Bollen_Pollen_3_26.mp3",
  "audio/word/Bolymer_Polymer_3_24.mp3",
  "audio/word/Brain_Prain_3_17.mp3",
  "audio/word/Brayer_Prayer_1_22.mp3",
  "audio/word/Breliminary_Preliminary_1_26.mp3",
  "audio/word/Bremier_Premier_3_21.mp3",
  "audio/word/Brewery_Prewery_1_17.mp3",
  "audio/word/Brimal_Primal_3_25.mp3",
  "audio/word/Brior_Prior_3_24.mp3",
  "audio/word/Browl_Prowl_3_20.mp3",
  "audio/word/Bry_Pry_1_24.mp3",
  "audio/word/Burial_Purial_1_20.mp3",
  "audio/word/Burrow_Purrow_3_15.mp3",
  "audio/word/Bylon_Pylon_1_19.mp3",
  "audio/word/Balloon_Palloon_3_16.mp3",
  "audio/word/Banana_Panana_3_17.mp3",
  "audio/word/Barn_Parn_1_16.mp3",
  "audio/word/Bawn_Pawn_3_25.mp3",
  "audio/word/Beninsula_Peninsula_3_28.mp3",
  "audio/word/Berform_Perform_3_23.mp3",
  "audio/word/Billion_Pillion_3_22.mp3",
  "audio/word/Billionaire_Pillionaire_3_16.mp3",
  "audio/word/Boom_Poom_1_20.mp3",
  "audio/word/Brime_Prime_1_20.mp3",
  "audio/word/Brown_Prown_3_15.mp3",
  "audio/word/Ballerina_Pallerina_1_20.mp3",
  "audio/word/Baloney_Paloney_1_15.mp3",
  "audio/word/Barallel_Parallel_3_22.mp3",
  "audio/word/Barely_Parely_1_15.mp3",
  "audio/word/Barlor_Parlor_3_26.mp3",
  "audio/word/Barren_Parren_3_17.mp3",
  "audio/word/Belly_Pelly_3_24.mp3",
  "audio/word/Benign_Penign_3_15.mp3",
  "audio/word/Biannual_Piannual_3_12.mp3",
  "audio/word/Bioneer_Pioneer_3_25.mp3",
  "audio/word/Blanner_Planner_3_27.mp3",
  "audio/word/Blea_Plea_3_23.mp3",
  "audio/word/Blue_Plue_3_21.mp3",
  "audio/word/Blyer_Plyer_1_22.mp3",
  "audio/word/Boil_Poil_1_19.mp3",
  "audio/word/Bollen_Pollen_3_28.mp3",
  "audio/word/Bolymer_Polymer_3_26.mp3",
  "audio/word/Brain_Prain_3_19.mp3",
  "audio/word/Brayer_Prayer_1_24.mp3",
  "audio/word/Breliminary_Preliminary_1_28.mp3",
  "audio/word/Bremier_Premier_3_23.mp3",
  "audio/word/Brewery_Prewery_1_19.mp3",
  "audio/word/Brimal_Primal_3_27.mp3",
  "audio/word/Brior_Prior_3_26.mp3",
  "audio/word/Browl_Prowl_3_22.mp3",
  "audio/word/Bry_Pry_1_26.mp3",
  "audio/word/Burial_Purial_1_22.mp3",
  "audio/word/Burrow_Purrow_3_17.mp3",
  "audio/word/Bylon_Pylon_1_21.mp3",
  "audio/nonword/balinomy_palinomy_1_23.mp3",
  "audio/nonword/baln_paln_3_20.mp3",
  "audio/nonword/bamurre_pamurre_3_22.mp3",
  "audio/nonword/bangle_pangle_3_24.mp3",
  "audio/nonword/barema_parema_3_17.mp3",
  "audio/nonword/barl_parl_3_19.mp3",
  "audio/nonword/belammer_pelammer_3_16.mp3",
  "audio/nonword/bellon_pellon_1_19.mp3",
  "audio/nonword/bemmela_pemmela_3_23.mp3",
  "audio/nonword/bemmerle_pemmerle_3_22.mp3",
  "audio/nonword/benlow_penlow_1_18.mp3",
  "audio/nonword/bennim_pennim_3_21.mp3",
  "audio/nonword/bim_pim_3_16.mp3",
  "audio/nonword/bimmel_pimmel_1_24.mp3",
  "audio/nonword/binneran_pinneran_1_16.mp3",
  "audio/nonword/borl_porl_3_15.mp3",
  "audio/nonword/boyer_poyer_3_15.mp3",
  "audio/nonword/brynon_prynon_1_22.mp3",
  "audio/nonword/bunnel_punnel_3_23.mp3",
  "audio/nonword/Bewry_Pewry_1_18.mp3",
  "audio/nonword/balinomy_palinomy_1_19.mp3",
  "audio/nonword/baln_paln_3_16.mp3",
  "audio/nonword/bamurre_pamurre_3_18.mp3",
  "audio/nonword/bangle_pangle_3_20.mp3",
  "audio/nonword/barema_parema_3_13.mp3",
  "audio/nonword/barl_parl_3_15.mp3",
  "audio/nonword/belammer_pelammer_3_12.mp3",
  "audio/nonword/bellon_pellon_1_15.mp3",
  "audio/nonword/bemmela_pemmela_3_19.mp3",
  "audio/nonword/bemmerle_pemmerle_3_18.mp3",
  "audio/nonword/benlow_penlow_1_14.mp3",
  "audio/nonword/bennim_pennim_3_17.mp3",
  "audio/nonword/bim_pim_3_12.mp3",
  "audio/nonword/bimmel_pimmel_1_20.mp3",
  "audio/nonword/binneran_pinneran_1_12.mp3",
  "audio/nonword/borl_porl_3_11.mp3",
  "audio/nonword/boyer_poyer_3_11.mp3",
  "audio/nonword/brynon_prynon_1_18.mp3",
  "audio/nonword/bunnel_punnel_3_19.mp3",
  "audio/nonword/Bewry_Pewry_1_14.mp3",
  "audio/nonword/balinomy_palinomy_1_21.mp3",
  "audio/nonword/baln_paln_3_18.mp3",
  "audio/nonword/bamurre_pamurre_3_20.mp3",
  "audio/nonword/bangle_pangle_3_22.mp3",
  "audio/nonword/barema_parema_3_15.mp3",
  "audio/nonword/barl_parl_3_17.mp3",
  "audio/nonword/belammer_pelammer_3_14.mp3",
  "audio/nonword/bellon_pellon_1_17.mp3",
  "audio/nonword/bemmela_pemmela_3_21.mp3",
  "audio/nonword/bemmerle_pemmerle_3_20.mp3",
  "audio/nonword/benlow_penlow_1_16.mp3",
  "audio/nonword/bennim_pennim_3_19.mp3",
  "audio/nonword/bim_pim_3_14.mp3",
  "audio/nonword/bimmel_pimmel_1_22.mp3",
  "audio/nonword/binneran_pinneran_1_14.mp3",
  "audio/nonword/borl_porl_3_13.mp3",
  "audio/nonword/boyer_poyer_3_13.mp3",
  "audio/nonword/brynon_prynon_1_20.mp3",
  "audio/nonword/bunnel_punnel_3_21.mp3",
  "audio/nonword/Bewry_Pewry_1_16.mp3",
  "audio/nonword/balinomy_palinomy_1_25.mp3",
  "audio/nonword/baln_paln_3_22.mp3",
  "audio/nonword/bamurre_pamurre_3_24.mp3",
  "audio/nonword/bangle_pangle_3_26.mp3",
  "audio/nonword/barema_parema_3_19.mp3",
  "audio/nonword/barl_parl_3_21.mp3",
  "audio/nonword/belammer_pelammer_3_18.mp3",
  "audio/nonword/bellon_pellon_1_21.mp3",
  "audio/nonword/bemmela_pemmela_3_25.mp3",
  "audio/nonword/bemmerle_pemmerle_3_24.mp3",
  "audio/nonword/benlow_penlow_1_20.mp3",
  "audio/nonword/bennim_pennim_3_23.mp3",
  "audio/nonword/bim_pim_3_18.mp3",
  "audio/nonword/bimmel_pimmel_1_26.mp3",
  "audio/nonword/binneran_pinneran_1_18.mp3",
  "audio/nonword/borl_porl_3_17.mp3",
  "audio/nonword/boyer_poyer_3_17.mp3",
  "audio/nonword/brynon_prynon_1_24.mp3",
  "audio/nonword/bunnel_punnel_3_25.mp3",
  "audio/nonword/Bewry_Pewry_1_20.mp3",
  "audio/nonword/balinomy_palinomy_1_27.mp3",
  "audio/nonword/baln_paln_3_24.mp3",
  "audio/nonword/bamurre_pamurre_3_26.mp3",
  "audio/nonword/bangle_pangle_3_28.mp3",
  "audio/nonword/barema_parema_3_21.mp3",
  "audio/nonword/barl_parl_3_23.mp3",
  "audio/nonword/belammer_pelammer_3_20.mp3",
  "audio/nonword/bellon_pellon_1_23.mp3",
  "audio/nonword/bemmela_pemmela_3_27.mp3",
  "audio/nonword/bemmerle_pemmerle_3_26.mp3",
  "audio/nonword/benlow_penlow_1_22.mp3",
  "audio/nonword/bennim_pennim_3_25.mp3",
  "audio/nonword/bim_pim_3_20.mp3",
  "audio/nonword/bimmel_pimmel_1_28.mp3",
  "audio/nonword/binneran_pinneran_1_20.mp3",
  "audio/nonword/borl_porl_3_19.mp3",
  "audio/nonword/boyer_poyer_3_19.mp3",
  "audio/nonword/brynon_prynon_1_26.mp3",
  "audio/nonword/bunnel_punnel_3_27.mp3",
  "audio/nonword/Bewry_Pewry_1_22.mp3"
]