
var possible_nonword_trial_stimuli = [
  {
    "index": "1",
    "set": "BAA_PAA_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "categorization",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_3_21.mp3"
  },
  {
    "index": "2",
    "set": "BAA_PAA_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "categorization",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_3_15.mp3"
  },
  {
    "index": "3",
    "set": "BAA_PAA_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "categorization",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_3_17.mp3"
  },
  {
    "index": "4",
    "set": "BAA_PAA_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "categorization",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_3_19.mp3"
  },
  {
    "index": "5",
    "set": "BAA_PAA_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "categorization",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_3_23.mp3"
  },
  {
    "index": "6",
    "set": "BAA_PAA_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "categorization",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_3_25.mp3"
  },
  {
    "index": "7",
    "set": "BAA_PAA_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "categorization",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "BAA_PAA_3_27.mp3"
  },
  {
    "index": "8",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_12.mp3"
  },
  {
    "index": "9",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "6",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_6.mp3"
  },
  {
    "index": "10",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_8.mp3"
  },
  {
    "index": "11",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_10.mp3"
  },
  {
    "index": "12",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_14.mp3"
  },
  {
    "index": "13",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_16.mp3"
  },
  {
    "index": "14",
    "set": "Ballerina_Pallerina_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Ballerina_Pallerina_1_18.mp3"
  },
  {
    "index": "15",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_19.mp3"
  },
  {
    "index": "16",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_13.mp3"
  },
  {
    "index": "17",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_15.mp3"
  },
  {
    "index": "18",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_17.mp3"
  },
  {
    "index": "19",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_21.mp3"
  },
  {
    "index": "20",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_23.mp3"
  },
  {
    "index": "21",
    "set": "Banana_Panana_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Banana_Panana_3_25.mp3"
  },
  {
    "index": "22",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_16.mp3"
  },
  {
    "index": "23",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_10.mp3"
  },
  {
    "index": "24",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_12.mp3"
  },
  {
    "index": "25",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_14.mp3"
  },
  {
    "index": "26",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_18.mp3"
  },
  {
    "index": "27",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_20.mp3"
  },
  {
    "index": "28",
    "set": "barl_parl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "barl_parl_3_22.mp3"
  },
  {
    "index": "29",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_22.mp3"
  },
  {
    "index": "30",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_16.mp3"
  },
  {
    "index": "31",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_18.mp3"
  },
  {
    "index": "32",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_20.mp3"
  },
  {
    "index": "33",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_24.mp3"
  },
  {
    "index": "34",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_26.mp3"
  },
  {
    "index": "35",
    "set": "Barn_Parn_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Barn_Parn_1_28.mp3"
  },
  {
    "index": "36",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_18.mp3"
  },
  {
    "index": "37",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_20.mp3"
  },
  {
    "index": "38",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_22.mp3"
  },
  {
    "index": "39",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_24.mp3"
  },
  {
    "index": "40",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_26.mp3"
  },
  {
    "index": "41",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_28.mp3"
  },
  {
    "index": "42",
    "set": "Bawn_Pawn_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "30",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bawn_Pawn_3_30.mp3"
  },
  {
    "index": "43",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_21.mp3"
  },
  {
    "index": "44",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_15.mp3"
  },
  {
    "index": "45",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_17.mp3"
  },
  {
    "index": "46",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_19.mp3"
  },
  {
    "index": "47",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_23.mp3"
  },
  {
    "index": "48",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_25.mp3"
  },
  {
    "index": "49",
    "set": "bemmela_pemmela_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bemmela_pemmela_3_27.mp3"
  },
  {
    "index": "50",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_20.mp3"
  },
  {
    "index": "51",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_14.mp3"
  },
  {
    "index": "52",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_16.mp3"
  },
  {
    "index": "53",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_18.mp3"
  },
  {
    "index": "54",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_22.mp3"
  },
  {
    "index": "55",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_24.mp3"
  },
  {
    "index": "56",
    "set": "Benign_Penign_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Benign_Penign_3_26.mp3"
  },
  {
    "index": "57",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_20.mp3"
  },
  {
    "index": "58",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_14.mp3"
  },
  {
    "index": "59",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_16.mp3"
  },
  {
    "index": "60",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_18.mp3"
  },
  {
    "index": "61",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_22.mp3"
  },
  {
    "index": "62",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_24.mp3"
  },
  {
    "index": "63",
    "set": "Beninsula_Peninsula_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Beninsula_Peninsula_3_26.mp3"
  },
  {
    "index": "64",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_18.mp3"
  },
  {
    "index": "65",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_20.mp3"
  },
  {
    "index": "66",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_22.mp3"
  },
  {
    "index": "67",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_24.mp3"
  },
  {
    "index": "68",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_26.mp3"
  },
  {
    "index": "69",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_28.mp3"
  },
  {
    "index": "70",
    "set": "Berform_Perform_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "30",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Berform_Perform_3_30.mp3"
  },
  {
    "index": "71",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_12.mp3"
  },
  {
    "index": "72",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "6",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_6.mp3"
  },
  {
    "index": "73",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_8.mp3"
  },
  {
    "index": "74",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_10.mp3"
  },
  {
    "index": "75",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_14.mp3"
  },
  {
    "index": "76",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_16.mp3"
  },
  {
    "index": "77",
    "set": "Billion_Pillion_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Billion_Pillion_3_18.mp3"
  },
  {
    "index": "78",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_16.mp3"
  },
  {
    "index": "79",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_10.mp3"
  },
  {
    "index": "80",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_12.mp3"
  },
  {
    "index": "81",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_14.mp3"
  },
  {
    "index": "82",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_18.mp3"
  },
  {
    "index": "83",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_20.mp3"
  },
  {
    "index": "84",
    "set": "bimmel_pimmel_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bimmel_pimmel_1_22.mp3"
  },
  {
    "index": "85",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_24.mp3"
  },
  {
    "index": "86",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_18.mp3"
  },
  {
    "index": "87",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_20.mp3"
  },
  {
    "index": "88",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_22.mp3"
  },
  {
    "index": "89",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_26.mp3"
  },
  {
    "index": "90",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_28.mp3"
  },
  {
    "index": "91",
    "set": "Bioneer_Pioneer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "30",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bioneer_Pioneer_3_30.mp3"
  },
  {
    "index": "92",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_21.mp3"
  },
  {
    "index": "93",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_15.mp3"
  },
  {
    "index": "94",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_17.mp3"
  },
  {
    "index": "95",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_19.mp3"
  },
  {
    "index": "96",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_23.mp3"
  },
  {
    "index": "97",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_25.mp3"
  },
  {
    "index": "98",
    "set": "Blea_Plea_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blea_Plea_3_27.mp3"
  },
  {
    "index": "99",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_22.mp3"
  },
  {
    "index": "100",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_16.mp3"
  },
  {
    "index": "101",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_18.mp3"
  },
  {
    "index": "102",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_20.mp3"
  },
  {
    "index": "103",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_24.mp3"
  },
  {
    "index": "104",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_26.mp3"
  },
  {
    "index": "105",
    "set": "Blyer_Plyer_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Blyer_Plyer_1_28.mp3"
  },
  {
    "index": "106",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_21.mp3"
  },
  {
    "index": "107",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_15.mp3"
  },
  {
    "index": "108",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_17.mp3"
  },
  {
    "index": "109",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_19.mp3"
  },
  {
    "index": "110",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_23.mp3"
  },
  {
    "index": "111",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_25.mp3"
  },
  {
    "index": "112",
    "set": "Bolymer_Polymer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bolymer_Polymer_3_27.mp3"
  },
  {
    "index": "113",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_22.mp3"
  },
  {
    "index": "114",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_16.mp3"
  },
  {
    "index": "115",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_18.mp3"
  },
  {
    "index": "116",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_20.mp3"
  },
  {
    "index": "117",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_24.mp3"
  },
  {
    "index": "118",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_26.mp3"
  },
  {
    "index": "119",
    "set": "borl_porl_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "borl_porl_3_28.mp3"
  },
  {
    "index": "120",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_22.mp3"
  },
  {
    "index": "121",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_16.mp3"
  },
  {
    "index": "122",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_18.mp3"
  },
  {
    "index": "123",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_20.mp3"
  },
  {
    "index": "124",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_24.mp3"
  },
  {
    "index": "125",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_26.mp3"
  },
  {
    "index": "126",
    "set": "boyer_poyer_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "boyer_poyer_3_28.mp3"
  },
  {
    "index": "127",
    "set": "Breliminary_Preliminary_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_3_24.mp3"
  },
  {
    "index": "128",
    "set": "Breliminary_Preliminary_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_3_28.mp3"
  },
  {
    "index": "129",
    "set": "Breliminary_Preliminary_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_3_20.mp3"
  },
  {
    "index": "130",
    "set": "Breliminary_Preliminary_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_3_22.mp3"
  },
  {
    "index": "131",
    "set": "Breliminary_Preliminary_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_3_26.mp3"
  },
  {
    "index": "132",
    "set": "Breliminary_Preliminary_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_3_28.mp3"
  },
  {
    "index": "133",
    "set": "Breliminary_Preliminary_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "30",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Breliminary_Preliminary_3_30.mp3"
  },
  {
    "index": "134",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_23.mp3"
  },
  {
    "index": "135",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_17.mp3"
  },
  {
    "index": "136",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_19.mp3"
  },
  {
    "index": "137",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_21.mp3"
  },
  {
    "index": "138",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_25.mp3"
  },
  {
    "index": "139",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "27",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_27.mp3"
  },
  {
    "index": "140",
    "set": "Bremier_Premier_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "29",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bremier_Premier_3_29.mp3"
  },
  {
    "index": "141",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_20.mp3"
  },
  {
    "index": "142",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_14.mp3"
  },
  {
    "index": "143",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_16.mp3"
  },
  {
    "index": "144",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_18.mp3"
  },
  {
    "index": "145",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_22.mp3"
  },
  {
    "index": "146",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_24.mp3"
  },
  {
    "index": "147",
    "set": "Brimal_Primal_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brimal_Primal_3_26.mp3"
  },
  {
    "index": "148",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_22.mp3"
  },
  {
    "index": "149",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_16.mp3"
  },
  {
    "index": "150",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_18.mp3"
  },
  {
    "index": "151",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_20.mp3"
  },
  {
    "index": "152",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_24.mp3"
  },
  {
    "index": "153",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_26.mp3"
  },
  {
    "index": "154",
    "set": "Brime_Prime_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Brime_Prime_1_28.mp3"
  },
  {
    "index": "155",
    "set": "Browl_Prowl_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_1_19.mp3"
  },
  {
    "index": "156",
    "set": "Browl_Prowl_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_1_13.mp3"
  },
  {
    "index": "157",
    "set": "Browl_Prowl_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_1_15.mp3"
  },
  {
    "index": "158",
    "set": "Browl_Prowl_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_1_17.mp3"
  },
  {
    "index": "159",
    "set": "Browl_Prowl_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "21",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_1_21.mp3"
  },
  {
    "index": "160",
    "set": "Browl_Prowl_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "23",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_1_23.mp3"
  },
  {
    "index": "161",
    "set": "Browl_Prowl_1",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "25",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Browl_Prowl_1_25.mp3"
  },
  {
    "index": "162",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_24.mp3"
  },
  {
    "index": "163",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_18.mp3"
  },
  {
    "index": "164",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_20.mp3"
  },
  {
    "index": "165",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_22.mp3"
  },
  {
    "index": "166",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_26.mp3"
  },
  {
    "index": "167",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_28.mp3"
  },
  {
    "index": "168",
    "set": "bunnel_punnel_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_nonword",
    "step": "30",
    "underscore": "_",
    "extension": ".mp3",
    "path": "bunnel_punnel_3_30.mp3"
  },
  {
    "index": "169",
    "set": "Bylon_Pylon_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_3_22.mp3"
  },
  {
    "index": "170",
    "set": "Bylon_Pylon_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_3_16.mp3"
  },
  {
    "index": "171",
    "set": "Bylon_Pylon_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_3_18.mp3"
  },
  {
    "index": "172",
    "set": "Bylon_Pylon_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_3_20.mp3"
  },
  {
    "index": "173",
    "set": "Bylon_Pylon_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_3_24.mp3"
  },
  {
    "index": "174",
    "set": "Bylon_Pylon_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_3_26.mp3"
  },
  {
    "index": "175",
    "set": "Bylon_Pylon_3",
    "voiced": "B",
    "voiceless": "P",
    "type": "exposure_word",
    "step": "28",
    "underscore": "_",
    "extension": ".mp3",
    "path": "Bylon_Pylon_3_28.mp3"
  }
]

var mp_trial_stimuli = [
  {
    "index": "1",
    "set": "dame_tame_1",
    "voiced": "Dame",
    "voiceless": "Tame",
    "type": "MP",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dame_tame_1_8.mp3",
    "": ""
  },
  {
    "index": "2",
    "set": "dare_tear_1",
    "voiced": "Dare",
    "voiceless": "Tear",
    "type": "MP",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dare_tear_1_11.mp3",
    "": ""
  },
  {
    "index": "3",
    "set": "deal_teal_3",
    "voiced": "Deal",
    "voiceless": "Teal",
    "type": "MP",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "deal_teal_3_18.mp3",
    "": ""
  },
  {
    "index": "4",
    "set": "doom_toom_3",
    "voiced": "Doom",
    "voiceless": "Tomb",
    "type": "MP",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "doom_toom_3_7.mp3",
    "": ""
  },
  {
    "index": "5",
    "set": "dough_toe_3",
    "voiced": "Dough",
    "voiceless": "Toe",
    "type": "MP",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dough_toe_3_9.mp3",
    "": ""
  },
  {
    "index": "6",
    "set": "drain_train_1",
    "voiced": "Drain",
    "voiceless": "Train",
    "type": "MP",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "drain_train_1_7.mp3",
    "": ""
  },
  {
    "index": "7",
    "set": "dry_try_3",
    "voiced": "Dry",
    "voiceless": "Try",
    "type": "MP",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dry_try_3_13.mp3",
    "": ""
  },
  {
    "index": "8",
    "set": "gale_kale_1",
    "voiced": "Gale",
    "voiceless": "Kale",
    "type": "MP",
    "step": "8",
    "underscore": "_",
    "extension": ".mp3",
    "path": "gale_kale_1_8.mp3",
    "": ""
  },
  {
    "index": "9",
    "set": "grill_krill_1",
    "voiced": "Grill",
    "voiceless": "Krill",
    "type": "MP",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grill_krill_1_20.mp3",
    "": ""
  },
  {
    "index": "10",
    "set": "grime_crime_3",
    "voiced": "Grime",
    "voiceless": "Crime",
    "type": "MP",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grime_crime_3_7.mp3",
    "": ""
  },
  {
    "index": "11",
    "set": "dame_tame_1",
    "voiced": "Dame",
    "voiceless": "Tame",
    "type": "MP",
    "step": "2",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dame_tame_1_2.mp3",
    "": ""
  },
  {
    "index": "12",
    "set": "dare_tear_1",
    "voiced": "Dare",
    "voiceless": "Tear",
    "type": "MP",
    "step": "5",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dare_tear_1_5.mp3",
    "": ""
  },
  {
    "index": "13",
    "set": "deal_teal_3",
    "voiced": "Deal",
    "voiceless": "Teal",
    "type": "MP",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "deal_teal_3_12.mp3",
    "": ""
  },
  {
    "index": "14",
    "set": "doom_toom_3",
    "voiced": "Doom",
    "voiceless": "Tomb",
    "type": "MP",
    "step": "1",
    "underscore": "_",
    "extension": ".mp3",
    "path": "doom_toom_3_1.mp3",
    "": ""
  },
  {
    "index": "15",
    "set": "dough_toe_3",
    "voiced": "Dough",
    "voiceless": "Toe",
    "type": "MP",
    "step": "3",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dough_toe_3_3.mp3",
    "": ""
  },
  {
    "index": "16",
    "set": "drain_train_1",
    "voiced": "Drain",
    "voiceless": "Train",
    "type": "MP",
    "step": "1",
    "underscore": "_",
    "extension": ".mp3",
    "path": "drain_train_1_1.mp3",
    "": ""
  },
  {
    "index": "17",
    "set": "dry_try_3",
    "voiced": "Dry",
    "voiceless": "Try",
    "type": "MP",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dry_try_3_7.mp3",
    "": ""
  },
  {
    "index": "18",
    "set": "gale_kale_1",
    "voiced": "Gale",
    "voiceless": "Kale",
    "type": "MP",
    "step": "2",
    "underscore": "_",
    "extension": ".mp3",
    "path": "gale_kale_1_2.mp3",
    "": ""
  },
  {
    "index": "19",
    "set": "grill_krill_1",
    "voiced": "Grill",
    "voiceless": "Krill",
    "type": "MP",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grill_krill_1_14.mp3",
    "": ""
  },
  {
    "index": "20",
    "set": "grime_crime_3",
    "voiced": "Grime",
    "voiceless": "Crime",
    "type": "MP",
    "step": "1",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grime_crime_3_1.mp3",
    "": ""
  },
  {
    "index": "21",
    "set": "dame_tame_1",
    "voiced": "Dame",
    "voiceless": "Tame",
    "type": "MP",
    "step": "4",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dame_tame_1_4.mp3",
    "": ""
  },
  {
    "index": "22",
    "set": "dare_tear_1",
    "voiced": "Dare",
    "voiceless": "Tear",
    "type": "MP",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dare_tear_1_7.mp3",
    "": ""
  },
  {
    "index": "23",
    "set": "deal_teal_3",
    "voiced": "Deal",
    "voiceless": "Teal",
    "type": "MP",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "deal_teal_3_14.mp3",
    "": ""
  },
  {
    "index": "24",
    "set": "doom_toom_3",
    "voiced": "Doom",
    "voiceless": "Tomb",
    "type": "MP",
    "step": "3",
    "underscore": "_",
    "extension": ".mp3",
    "path": "doom_toom_3_3.mp3",
    "": ""
  },
  {
    "index": "25",
    "set": "dough_toe_3",
    "voiced": "Dough",
    "voiceless": "Toe",
    "type": "MP",
    "step": "5",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dough_toe_3_5.mp3",
    "": ""
  },
  {
    "index": "26",
    "set": "drain_train_1",
    "voiced": "Drain",
    "voiceless": "Train",
    "type": "MP",
    "step": "3",
    "underscore": "_",
    "extension": ".mp3",
    "path": "drain_train_1_3.mp3",
    "": ""
  },
  {
    "index": "27",
    "set": "dry_try_3",
    "voiced": "Dry",
    "voiceless": "Try",
    "type": "MP",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dry_try_3_9.mp3",
    "": ""
  },
  {
    "index": "28",
    "set": "gale_kale_1",
    "voiced": "Gale",
    "voiceless": "Kale",
    "type": "MP",
    "step": "4",
    "underscore": "_",
    "extension": ".mp3",
    "path": "gale_kale_1_4.mp3",
    "": ""
  },
  {
    "index": "29",
    "set": "grill_krill_1",
    "voiced": "Grill",
    "voiceless": "Krill",
    "type": "MP",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grill_krill_1_16.mp3",
    "": ""
  },
  {
    "index": "30",
    "set": "grime_crime_3",
    "voiced": "Grime",
    "voiceless": "Crime",
    "type": "MP",
    "step": "3",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grime_crime_3_3.mp3",
    "": ""
  },
  {
    "index": "31",
    "set": "dame_tame_1",
    "voiced": "Dame",
    "voiceless": "Tame",
    "type": "MP",
    "step": "6",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dame_tame_1_6.mp3",
    "": ""
  },
  {
    "index": "32",
    "set": "dare_tear_1",
    "voiced": "Dare",
    "voiceless": "Tear",
    "type": "MP",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dare_tear_1_9.mp3",
    "": ""
  },
  {
    "index": "33",
    "set": "deal_teal_3",
    "voiced": "Deal",
    "voiceless": "Teal",
    "type": "MP",
    "step": "16",
    "underscore": "_",
    "extension": ".mp3",
    "path": "deal_teal_3_16.mp3",
    "": ""
  },
  {
    "index": "34",
    "set": "doom_toom_3",
    "voiced": "Doom",
    "voiceless": "Tomb",
    "type": "MP",
    "step": "5",
    "underscore": "_",
    "extension": ".mp3",
    "path": "doom_toom_3_5.mp3",
    "": ""
  },
  {
    "index": "35",
    "set": "dough_toe_3",
    "voiced": "Dough",
    "voiceless": "Toe",
    "type": "MP",
    "step": "7",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dough_toe_3_7.mp3",
    "": ""
  },
  {
    "index": "36",
    "set": "drain_train_1",
    "voiced": "Drain",
    "voiceless": "Train",
    "type": "MP",
    "step": "5",
    "underscore": "_",
    "extension": ".mp3",
    "path": "drain_train_1_5.mp3",
    "": ""
  },
  {
    "index": "37",
    "set": "dry_try_3",
    "voiced": "Dry",
    "voiceless": "Try",
    "type": "MP",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dry_try_3_11.mp3",
    "": ""
  },
  {
    "index": "38",
    "set": "gale_kale_1",
    "voiced": "Gale",
    "voiceless": "Kale",
    "type": "MP",
    "step": "6",
    "underscore": "_",
    "extension": ".mp3",
    "path": "gale_kale_1_6.mp3",
    "": ""
  },
  {
    "index": "39",
    "set": "grill_krill_1",
    "voiced": "Grill",
    "voiceless": "Krill",
    "type": "MP",
    "step": "18",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grill_krill_1_18.mp3",
    "": ""
  },
  {
    "index": "40",
    "set": "grime_crime_3",
    "voiced": "Grime",
    "voiceless": "Crime",
    "type": "MP",
    "step": "5",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grime_crime_3_5.mp3",
    "": ""
  },
  {
    "index": "41",
    "set": "dame_tame_1",
    "voiced": "Dame",
    "voiceless": "Tame",
    "type": "MP",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dame_tame_1_10.mp3",
    "": ""
  },
  {
    "index": "42",
    "set": "dare_tear_1",
    "voiced": "Dare",
    "voiceless": "Tear",
    "type": "MP",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dare_tear_1_13.mp3",
    "": ""
  },
  {
    "index": "43",
    "set": "deal_teal_3",
    "voiced": "Deal",
    "voiceless": "Teal",
    "type": "MP",
    "step": "20",
    "underscore": "_",
    "extension": ".mp3",
    "path": "deal_teal_3_20.mp3",
    "": ""
  },
  {
    "index": "44",
    "set": "doom_toom_3",
    "voiced": "Doom",
    "voiceless": "Tomb",
    "type": "MP",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "doom_toom_3_9.mp3",
    "": ""
  },
  {
    "index": "45",
    "set": "dough_toe_3",
    "voiced": "Dough",
    "voiceless": "Toe",
    "type": "MP",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dough_toe_3_11.mp3",
    "": ""
  },
  {
    "index": "46",
    "set": "drain_train_1",
    "voiced": "Drain",
    "voiceless": "Train",
    "type": "MP",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "drain_train_1_9.mp3",
    "": ""
  },
  {
    "index": "47",
    "set": "dry_try_3",
    "voiced": "Dry",
    "voiceless": "Try",
    "type": "MP",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dry_try_3_15.mp3",
    "": ""
  },
  {
    "index": "48",
    "set": "gale_kale_1",
    "voiced": "Gale",
    "voiceless": "Kale",
    "type": "MP",
    "step": "10",
    "underscore": "_",
    "extension": ".mp3",
    "path": "gale_kale_1_10.mp3",
    "": ""
  },
  {
    "index": "49",
    "set": "grill_krill_1",
    "voiced": "Grill",
    "voiceless": "Krill",
    "type": "MP",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grill_krill_1_22.mp3",
    "": ""
  },
  {
    "index": "50",
    "set": "grime_crime_3",
    "voiced": "Grime",
    "voiceless": "Crime",
    "type": "MP",
    "step": "9",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grime_crime_3_9.mp3",
    "": ""
  },
  {
    "index": "51",
    "set": "dame_tame_1",
    "voiced": "Dame",
    "voiceless": "Tame",
    "type": "MP",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dame_tame_1_12.mp3",
    "": ""
  },
  {
    "index": "52",
    "set": "dare_tear_1",
    "voiced": "Dare",
    "voiceless": "Tear",
    "type": "MP",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dare_tear_1_15.mp3",
    "": ""
  },
  {
    "index": "53",
    "set": "deal_teal_3",
    "voiced": "Deal",
    "voiceless": "Teal",
    "type": "MP",
    "step": "22",
    "underscore": "_",
    "extension": ".mp3",
    "path": "deal_teal_3_22.mp3",
    "": ""
  },
  {
    "index": "54",
    "set": "doom_toom_3",
    "voiced": "Doom",
    "voiceless": "Tomb",
    "type": "MP",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "doom_toom_3_11.mp3",
    "": ""
  },
  {
    "index": "55",
    "set": "dough_toe_3",
    "voiced": "Dough",
    "voiceless": "Toe",
    "type": "MP",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dough_toe_3_13.mp3",
    "": ""
  },
  {
    "index": "56",
    "set": "drain_train_1",
    "voiced": "Drain",
    "voiceless": "Train",
    "type": "MP",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "drain_train_1_11.mp3",
    "": ""
  },
  {
    "index": "57",
    "set": "dry_try_3",
    "voiced": "Dry",
    "voiceless": "Try",
    "type": "MP",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dry_try_3_17.mp3",
    "": ""
  },
  {
    "index": "58",
    "set": "gale_kale_1",
    "voiced": "Gale",
    "voiceless": "Kale",
    "type": "MP",
    "step": "12",
    "underscore": "_",
    "extension": ".mp3",
    "path": "gale_kale_1_12.mp3",
    "": ""
  },
  {
    "index": "59",
    "set": "grill_krill_1",
    "voiced": "Grill",
    "voiceless": "Krill",
    "type": "MP",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grill_krill_1_24.mp3",
    "": ""
  },
  {
    "index": "60",
    "set": "grime_crime_3",
    "voiced": "Grime",
    "voiceless": "Crime",
    "type": "MP",
    "step": "11",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grime_crime_3_11.mp3",
    "": ""
  },
  {
    "index": "61",
    "set": "dame_tame_1",
    "voiced": "Dame",
    "voiceless": "Tame",
    "type": "MP",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dame_tame_1_14.mp3",
    "": ""
  },
  {
    "index": "62",
    "set": "dare_tear_1",
    "voiced": "Dare",
    "voiceless": "Tear",
    "type": "MP",
    "step": "17",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dare_tear_1_17.mp3",
    "": ""
  },
  {
    "index": "63",
    "set": "deal_teal_3",
    "voiced": "Deal",
    "voiceless": "Teal",
    "type": "MP",
    "step": "24",
    "underscore": "_",
    "extension": ".mp3",
    "path": "deal_teal_3_24.mp3",
    "": ""
  },
  {
    "index": "64",
    "set": "doom_toom_3",
    "voiced": "Doom",
    "voiceless": "Tomb",
    "type": "MP",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "doom_toom_3_13.mp3",
    "": ""
  },
  {
    "index": "65",
    "set": "dough_toe_3",
    "voiced": "Dough",
    "voiceless": "Toe",
    "type": "MP",
    "step": "15",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dough_toe_3_15.mp3",
    "": ""
  },
  {
    "index": "66",
    "set": "drain_train_1",
    "voiced": "Drain",
    "voiceless": "Train",
    "type": "MP",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "drain_train_1_13.mp3",
    "": ""
  },
  {
    "index": "67",
    "set": "dry_try_3",
    "voiced": "Dry",
    "voiceless": "Try",
    "type": "MP",
    "step": "19",
    "underscore": "_",
    "extension": ".mp3",
    "path": "dry_try_3_19.mp3",
    "": ""
  },
  {
    "index": "68",
    "set": "gale_kale_1",
    "voiced": "Gale",
    "voiceless": "Kale",
    "type": "MP",
    "step": "14",
    "underscore": "_",
    "extension": ".mp3",
    "path": "gale_kale_1_14.mp3",
    "": ""
  },
  {
    "index": "69",
    "set": "grill_krill_1",
    "voiced": "Grill",
    "voiceless": "Krill",
    "type": "MP",
    "step": "26",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grill_krill_1_26.mp3",
    "": ""
  },
  {
    "index": "70",
    "set": "grime_crime_3",
    "voiced": "Grime",
    "voiceless": "Crime",
    "type": "MP",
    "step": "13",
    "underscore": "_",
    "extension": ".mp3",
    "path": "grime_crime_3_13.mp3",
    "": ""
  }
]

var assetPaths = [
  "audio/possible_nonword/BAA_PAA_3_21.mp3",
  "audio/possible_nonword/BAA_PAA_3_15.mp3",
  "audio/possible_nonword/BAA_PAA_3_17.mp3",
  "audio/possible_nonword/BAA_PAA_3_19.mp3",
  "audio/possible_nonword/BAA_PAA_3_23.mp3",
  "audio/possible_nonword/BAA_PAA_3_25.mp3",
  "audio/possible_nonword/BAA_PAA_3_27.mp3",
  "audio/possible_nonword/Ballerina_Pallerina_1_12.mp3",
  "audio/possible_nonword/Ballerina_Pallerina_1_6.mp3",
  "audio/possible_nonword/Ballerina_Pallerina_1_8.mp3",
  "audio/possible_nonword/Ballerina_Pallerina_1_10.mp3",
  "audio/possible_nonword/Ballerina_Pallerina_1_14.mp3",
  "audio/possible_nonword/Ballerina_Pallerina_1_16.mp3",
  "audio/possible_nonword/Ballerina_Pallerina_1_18.mp3",
  "audio/possible_nonword/Banana_Panana_3_19.mp3",
  "audio/possible_nonword/Banana_Panana_3_13.mp3",
  "audio/possible_nonword/Banana_Panana_3_15.mp3",
  "audio/possible_nonword/Banana_Panana_3_17.mp3",
  "audio/possible_nonword/Banana_Panana_3_21.mp3",
  "audio/possible_nonword/Banana_Panana_3_23.mp3",
  "audio/possible_nonword/Banana_Panana_3_25.mp3",
  "audio/possible_nonword/barl_parl_3_16.mp3",
  "audio/possible_nonword/barl_parl_3_10.mp3",
  "audio/possible_nonword/barl_parl_3_12.mp3",
  "audio/possible_nonword/barl_parl_3_14.mp3",
  "audio/possible_nonword/barl_parl_3_18.mp3",
  "audio/possible_nonword/barl_parl_3_20.mp3",
  "audio/possible_nonword/barl_parl_3_22.mp3",
  "audio/possible_nonword/Barn_Parn_1_22.mp3",
  "audio/possible_nonword/Barn_Parn_1_16.mp3",
  "audio/possible_nonword/Barn_Parn_1_18.mp3",
  "audio/possible_nonword/Barn_Parn_1_20.mp3",
  "audio/possible_nonword/Barn_Parn_1_24.mp3",
  "audio/possible_nonword/Barn_Parn_1_26.mp3",
  "audio/possible_nonword/Barn_Parn_1_28.mp3",
  "audio/possible_nonword/Bawn_Pawn_3_18.mp3",
  "audio/possible_nonword/Bawn_Pawn_3_20.mp3",
  "audio/possible_nonword/Bawn_Pawn_3_22.mp3",
  "audio/possible_nonword/Bawn_Pawn_3_24.mp3",
  "audio/possible_nonword/Bawn_Pawn_3_26.mp3",
  "audio/possible_nonword/Bawn_Pawn_3_28.mp3",
  "audio/possible_nonword/Bawn_Pawn_3_30.mp3",
  "audio/possible_nonword/bemmela_pemmela_3_21.mp3",
  "audio/possible_nonword/bemmela_pemmela_3_15.mp3",
  "audio/possible_nonword/bemmela_pemmela_3_17.mp3",
  "audio/possible_nonword/bemmela_pemmela_3_19.mp3",
  "audio/possible_nonword/bemmela_pemmela_3_23.mp3",
  "audio/possible_nonword/bemmela_pemmela_3_25.mp3",
  "audio/possible_nonword/bemmela_pemmela_3_27.mp3",
  "audio/possible_nonword/Benign_Penign_3_20.mp3",
  "audio/possible_nonword/Benign_Penign_3_14.mp3",
  "audio/possible_nonword/Benign_Penign_3_16.mp3",
  "audio/possible_nonword/Benign_Penign_3_18.mp3",
  "audio/possible_nonword/Benign_Penign_3_22.mp3",
  "audio/possible_nonword/Benign_Penign_3_24.mp3",
  "audio/possible_nonword/Benign_Penign_3_26.mp3",
  "audio/possible_nonword/Beninsula_Peninsula_3_20.mp3",
  "audio/possible_nonword/Beninsula_Peninsula_3_14.mp3",
  "audio/possible_nonword/Beninsula_Peninsula_3_16.mp3",
  "audio/possible_nonword/Beninsula_Peninsula_3_18.mp3",
  "audio/possible_nonword/Beninsula_Peninsula_3_22.mp3",
  "audio/possible_nonword/Beninsula_Peninsula_3_24.mp3",
  "audio/possible_nonword/Beninsula_Peninsula_3_26.mp3",
  "audio/possible_nonword/Berform_Perform_3_18.mp3",
  "audio/possible_nonword/Berform_Perform_3_20.mp3",
  "audio/possible_nonword/Berform_Perform_3_22.mp3",
  "audio/possible_nonword/Berform_Perform_3_24.mp3",
  "audio/possible_nonword/Berform_Perform_3_26.mp3",
  "audio/possible_nonword/Berform_Perform_3_28.mp3",
  "audio/possible_nonword/Berform_Perform_3_30.mp3",
  "audio/possible_nonword/Billion_Pillion_3_12.mp3",
  "audio/possible_nonword/Billion_Pillion_3_6.mp3",
  "audio/possible_nonword/Billion_Pillion_3_8.mp3",
  "audio/possible_nonword/Billion_Pillion_3_10.mp3",
  "audio/possible_nonword/Billion_Pillion_3_14.mp3",
  "audio/possible_nonword/Billion_Pillion_3_16.mp3",
  "audio/possible_nonword/Billion_Pillion_3_18.mp3",
  "audio/possible_nonword/bimmel_pimmel_1_16.mp3",
  "audio/possible_nonword/bimmel_pimmel_1_10.mp3",
  "audio/possible_nonword/bimmel_pimmel_1_12.mp3",
  "audio/possible_nonword/bimmel_pimmel_1_14.mp3",
  "audio/possible_nonword/bimmel_pimmel_1_18.mp3",
  "audio/possible_nonword/bimmel_pimmel_1_20.mp3",
  "audio/possible_nonword/bimmel_pimmel_1_22.mp3",
  "audio/possible_nonword/Bioneer_Pioneer_3_24.mp3",
  "audio/possible_nonword/Bioneer_Pioneer_3_18.mp3",
  "audio/possible_nonword/Bioneer_Pioneer_3_20.mp3",
  "audio/possible_nonword/Bioneer_Pioneer_3_22.mp3",
  "audio/possible_nonword/Bioneer_Pioneer_3_26.mp3",
  "audio/possible_nonword/Bioneer_Pioneer_3_28.mp3",
  "audio/possible_nonword/Bioneer_Pioneer_3_30.mp3",
  "audio/possible_nonword/Blea_Plea_3_21.mp3",
  "audio/possible_nonword/Blea_Plea_3_15.mp3",
  "audio/possible_nonword/Blea_Plea_3_17.mp3",
  "audio/possible_nonword/Blea_Plea_3_19.mp3",
  "audio/possible_nonword/Blea_Plea_3_23.mp3",
  "audio/possible_nonword/Blea_Plea_3_25.mp3",
  "audio/possible_nonword/Blea_Plea_3_27.mp3",
  "audio/possible_nonword/Blyer_Plyer_1_22.mp3",
  "audio/possible_nonword/Blyer_Plyer_1_16.mp3",
  "audio/possible_nonword/Blyer_Plyer_1_18.mp3",
  "audio/possible_nonword/Blyer_Plyer_1_20.mp3",
  "audio/possible_nonword/Blyer_Plyer_1_24.mp3",
  "audio/possible_nonword/Blyer_Plyer_1_26.mp3",
  "audio/possible_nonword/Blyer_Plyer_1_28.mp3",
  "audio/possible_nonword/Bolymer_Polymer_3_21.mp3",
  "audio/possible_nonword/Bolymer_Polymer_3_15.mp3",
  "audio/possible_nonword/Bolymer_Polymer_3_17.mp3",
  "audio/possible_nonword/Bolymer_Polymer_3_19.mp3",
  "audio/possible_nonword/Bolymer_Polymer_3_23.mp3",
  "audio/possible_nonword/Bolymer_Polymer_3_25.mp3",
  "audio/possible_nonword/Bolymer_Polymer_3_27.mp3",
  "audio/possible_nonword/borl_porl_3_22.mp3",
  "audio/possible_nonword/borl_porl_3_16.mp3",
  "audio/possible_nonword/borl_porl_3_18.mp3",
  "audio/possible_nonword/borl_porl_3_20.mp3",
  "audio/possible_nonword/borl_porl_3_24.mp3",
  "audio/possible_nonword/borl_porl_3_26.mp3",
  "audio/possible_nonword/borl_porl_3_28.mp3",
  "audio/possible_nonword/boyer_poyer_3_22.mp3",
  "audio/possible_nonword/boyer_poyer_3_16.mp3",
  "audio/possible_nonword/boyer_poyer_3_18.mp3",
  "audio/possible_nonword/boyer_poyer_3_20.mp3",
  "audio/possible_nonword/boyer_poyer_3_24.mp3",
  "audio/possible_nonword/boyer_poyer_3_26.mp3",
  "audio/possible_nonword/boyer_poyer_3_28.mp3",
  "audio/possible_nonword/Breliminary_Preliminary_3_24.mp3",
  "audio/possible_nonword/Breliminary_Preliminary_3_28.mp3",
  "audio/possible_nonword/Breliminary_Preliminary_3_20.mp3",
  "audio/possible_nonword/Breliminary_Preliminary_3_22.mp3",
  "audio/possible_nonword/Breliminary_Preliminary_3_26.mp3",
  "audio/possible_nonword/Breliminary_Preliminary_3_28.mp3",
  "audio/possible_nonword/Breliminary_Preliminary_3_30.mp3",
  "audio/possible_nonword/Bremier_Premier_3_23.mp3",
  "audio/possible_nonword/Bremier_Premier_3_17.mp3",
  "audio/possible_nonword/Bremier_Premier_3_19.mp3",
  "audio/possible_nonword/Bremier_Premier_3_21.mp3",
  "audio/possible_nonword/Bremier_Premier_3_25.mp3",
  "audio/possible_nonword/Bremier_Premier_3_27.mp3",
  "audio/possible_nonword/Bremier_Premier_3_29.mp3",
  "audio/possible_nonword/Brimal_Primal_3_20.mp3",
  "audio/possible_nonword/Brimal_Primal_3_14.mp3",
  "audio/possible_nonword/Brimal_Primal_3_16.mp3",
  "audio/possible_nonword/Brimal_Primal_3_18.mp3",
  "audio/possible_nonword/Brimal_Primal_3_22.mp3",
  "audio/possible_nonword/Brimal_Primal_3_24.mp3",
  "audio/possible_nonword/Brimal_Primal_3_26.mp3",
  "audio/possible_nonword/Brime_Prime_1_22.mp3",
  "audio/possible_nonword/Brime_Prime_1_16.mp3",
  "audio/possible_nonword/Brime_Prime_1_18.mp3",
  "audio/possible_nonword/Brime_Prime_1_20.mp3",
  "audio/possible_nonword/Brime_Prime_1_24.mp3",
  "audio/possible_nonword/Brime_Prime_1_26.mp3",
  "audio/possible_nonword/Brime_Prime_1_28.mp3",
  "audio/possible_nonword/Browl_Prowl_1_19.mp3",
  "audio/possible_nonword/Browl_Prowl_1_13.mp3",
  "audio/possible_nonword/Browl_Prowl_1_15.mp3",
  "audio/possible_nonword/Browl_Prowl_1_17.mp3",
  "audio/possible_nonword/Browl_Prowl_1_21.mp3",
  "audio/possible_nonword/Browl_Prowl_1_23.mp3",
  "audio/possible_nonword/Browl_Prowl_1_25.mp3",
  "audio/possible_nonword/bunnel_punnel_3_24.mp3",
  "audio/possible_nonword/bunnel_punnel_3_18.mp3",
  "audio/possible_nonword/bunnel_punnel_3_20.mp3",
  "audio/possible_nonword/bunnel_punnel_3_22.mp3",
  "audio/possible_nonword/bunnel_punnel_3_26.mp3",
  "audio/possible_nonword/bunnel_punnel_3_28.mp3",
  "audio/possible_nonword/bunnel_punnel_3_30.mp3",
  "audio/possible_nonword/Bylon_Pylon_3_22.mp3",
  "audio/possible_nonword/Bylon_Pylon_3_16.mp3",
  "audio/possible_nonword/Bylon_Pylon_3_18.mp3",
  "audio/possible_nonword/Bylon_Pylon_3_20.mp3",
  "audio/possible_nonword/Bylon_Pylon_3_24.mp3",
  "audio/possible_nonword/Bylon_Pylon_3_26.mp3",
  "audio/possible_nonword/Bylon_Pylon_3_28.mp3",
  "audio/mp/dame_tame_1_8.mp3",
  "audio/mp/dare_tear_1_11.mp3",
  "audio/mp/deal_teal_3_18.mp3",
  "audio/mp/doom_toom_3_7.mp3",
  "audio/mp/dough_toe_3_9.mp3",
  "audio/mp/drain_train_1_7.mp3",
  "audio/mp/dry_try_3_13.mp3",
  "audio/mp/gale_kale_1_8.mp3",
  "audio/mp/grill_krill_1_20.mp3",
  "audio/mp/grime_crime_3_7.mp3",
  "audio/mp/dame_tame_1_2.mp3",
  "audio/mp/dare_tear_1_5.mp3",
  "audio/mp/deal_teal_3_12.mp3",
  "audio/mp/doom_toom_3_1.mp3",
  "audio/mp/dough_toe_3_3.mp3",
  "audio/mp/drain_train_1_1.mp3",
  "audio/mp/dry_try_3_7.mp3",
  "audio/mp/gale_kale_1_2.mp3",
  "audio/mp/grill_krill_1_14.mp3",
  "audio/mp/grime_crime_3_1.mp3",
  "audio/mp/dame_tame_1_4.mp3",
  "audio/mp/dare_tear_1_7.mp3",
  "audio/mp/deal_teal_3_14.mp3",
  "audio/mp/doom_toom_3_3.mp3",
  "audio/mp/dough_toe_3_5.mp3",
  "audio/mp/drain_train_1_3.mp3",
  "audio/mp/dry_try_3_9.mp3",
  "audio/mp/gale_kale_1_4.mp3",
  "audio/mp/grill_krill_1_16.mp3",
  "audio/mp/grime_crime_3_3.mp3",
  "audio/mp/dame_tame_1_6.mp3",
  "audio/mp/dare_tear_1_9.mp3",
  "audio/mp/deal_teal_3_16.mp3",
  "audio/mp/doom_toom_3_5.mp3",
  "audio/mp/dough_toe_3_7.mp3",
  "audio/mp/drain_train_1_5.mp3",
  "audio/mp/dry_try_3_11.mp3",
  "audio/mp/gale_kale_1_6.mp3",
  "audio/mp/grill_krill_1_18.mp3",
  "audio/mp/grime_crime_3_5.mp3",
  "audio/mp/dame_tame_1_10.mp3",
  "audio/mp/dare_tear_1_13.mp3",
  "audio/mp/deal_teal_3_20.mp3",
  "audio/mp/doom_toom_3_9.mp3",
  "audio/mp/dough_toe_3_11.mp3",
  "audio/mp/drain_train_1_9.mp3",
  "audio/mp/dry_try_3_15.mp3",
  "audio/mp/gale_kale_1_10.mp3",
  "audio/mp/grill_krill_1_22.mp3",
  "audio/mp/grime_crime_3_9.mp3",
  "audio/mp/dame_tame_1_12.mp3",
  "audio/mp/dare_tear_1_15.mp3",
  "audio/mp/deal_teal_3_22.mp3",
  "audio/mp/doom_toom_3_11.mp3",
  "audio/mp/dough_toe_3_13.mp3",
  "audio/mp/drain_train_1_11.mp3",
  "audio/mp/dry_try_3_17.mp3",
  "audio/mp/gale_kale_1_12.mp3",
  "audio/mp/grill_krill_1_24.mp3",
  "audio/mp/grime_crime_3_11.mp3",
  "audio/mp/dame_tame_1_14.mp3",
  "audio/mp/dare_tear_1_17.mp3",
  "audio/mp/deal_teal_3_24.mp3",
  "audio/mp/doom_toom_3_13.mp3",
  "audio/mp/dough_toe_3_15.mp3",
  "audio/mp/drain_train_1_13.mp3",
  "audio/mp/dry_try_3_19.mp3",
  "audio/mp/gale_kale_1_14.mp3",
  "audio/mp/grill_krill_1_26.mp3",
  "audio/mp/grime_crime_3_13.mp3"
]